### ISSUE TITLE
Cannot address >1 default route via IPDB

### ISSUE THREAD

**Issue by tomislacker** [svinota/pyroute2#230] opened 2016-04-11 20:28 UTC
Multiple default gateways in the *main* table are not able to be referenced.

#### Setup
```sh
$ ip r sh table main
default via 172.16.3.254 dev enp0s25  proto static  metric 100 
default via 172.16.0.254 dev enp0s25  metric 1200 
172.16.0.0/22 dev enp0s25  proto kernel  scope link  src 172.16.0.69 
172.16.0.0/22 dev enp0s25  proto kernel  scope link  src 172.16.0.69  metric 100 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
```

```python
from pyroute2 import IPDB
ip = IPDB()
```

#### Listing Specifically Default Routes

```python
with ip.routes['default'] as rs:
    print rs
```

```json
{
    "metrics": {},
    "oif": 3,
    "dst_len": 0,
    "family": 2,
    "proto": 3,
    "tos": 0,
    "dst": "default",
    "flags": 0,
    "ipdb_priority": 0,
    "priority": 1200,
    "scope": 0,
    "src_len": 0,
    "table": 254,
    "multipath": [],
    "type": 1,
    "gateway": "172.16.0.254",
    "ipdb_scope": "system"
}
```

#### Listing All Routes

```python
[r for r in ip.routes if r['oif'] == 3]
```

```json
[
    {
        "metrics": {},
        "oif": 3,
        "dst_len": 0,
        "family": 2,
        "proto": 3,
        "tos": 0,
        "dst": "default",
        "flags": 0,
        "ipdb_priority": 0,
        "priority": 1200,
        "scope": 0,
        "src_len": 0,
        "table": 254,
        "multipath": [],
        "type": 1,
        "gateway": "172.16.0.254",
        "ipdb_scope": "system"
    },
    {
        "metrics": {},
        "oif": 3,
        "type": 1,
        "dst_len": 22,
        "family": 2,
        "proto": 2,
        "tos": 0,
        "dst": "172.16.0.0/22",
        "ipdb_priority": 0,
        "priority": 100,
        "flags": 0,
        "src_len": 0,
        "table": 254,
        "multipath": [],
        "prefsrc": "172.16.0.69",
        "scope": 253,
        "ipdb_scope": "system"
    },
    {
        "metrics": {},
        "oif": 3,
        "dst_len": 64,
        "family": 10,
        "proto": 2,
        "tos": 0,
        "dst": "fe80::/64",
        "pref": "00",
        "ipdb_priority": 0,
        "priority": 256,
        "flags": 0,
        "src_len": 0,
        "table": 254,
        "multipath": [],
        "type": 1,
        "scope": 0,
        "ipdb_scope": "system"
    }
]
```

**Comment by tomislacker** [comment] 2016-04-11 20:43
Additionally another strange case with default routes...

```python
from pyroute2 import IPDB
ip = IPDB(mode='implicit')

# Assume I have a single default route
#  default via 172.16.3.254 dev enp0s25  proto static  metric 100 
ip.routes['default']
>>> {'metrics': {}, 'oif': 3, 'dst_len': 0, 'family': 2, 'proto': 3, 'tos': 0, 'dst': 'default', 'flags': 0, 'ipdb_priority': 0, 'priority': 1200, 'scope': 0, 'src_len': 0, 'table': 254, 'multipath': [], 'type': 1, 'gateway': '172.16.0.254', 'ipdb_scope': 'system'}

# If I add the other route... I get that one
# ip r add default via 172.16.0.254 dev enp0s25 metric 1200
ip.routes['default']
>>> {'metrics': {}, 'oif': 3, 'dst_len': 0, 'family': 2, 'proto': 3, 'tos': 0, 'dst': 'default', 'flags': 0, 'ipdb_priority': 0, 'priority': 1200, 'scope': 0, 'src_len': 0, 'table': 254, 'multipath': [], 'type': 1, 'gateway': '172.16.0.254', 'ipdb_scope': 'system'}

# But now if I delete this most recently created default route and go
# to reference again, I get an exception
ip.routes['default']
```

```
---------------------------------------------------------------------------
NetlinkError                              Traceback (most recent call last)
<ipython-input-9-192806e3a01a> in <module>()
----> 1 ip.routes['default']

/myproject/venv/lib/python2.7/site-packages/pyroute2/ipdb/route.pyc in __getitem__(self, key)
    498 
    499     def __getitem__(self, key):
--> 500         return self.get(key)
    501 
    502     def __setitem__(self, key, value):

/myproject/venv/lib/python2.7/site-packages/pyroute2/ipdb/route.pyc in get(self, dst, table)
    484     def get(self, dst, table=None):
    485         table = table or 254
--> 486         return self.tables[table][dst]
    487 
    488     def keys(self, table=254, family=AF_UNSPEC):

/myproject/venv/lib/python2.7/site-packages/pyroute2/ipdb/route.pyc in __getitem__(self, key)
    393     def __getitem__(self, key):
    394         with self.lock:
--> 395             return self.describe(key, forward=True)['route']
    396 
    397     def __contains__(self, key):

/myproject/venv/lib/python2.7/site-packages/pyroute2/ipdb/route.pyc in describe(self, target, forward)
    356         # load and return the route, if exists
    357         route = Route(self.ipdb)
--> 358         route.load_netlink(self.ipdb.nl.get_routes(**target)[0])
    359         return {'route': route,
    360                 'key': None}

/myproject/venv/lib/python2.7/site-packages/pyroute2/iproute.pyc in get_routes(self, family, match, **kwarg)
    382 
    383         return self.route((RTM_GETROUTE, msg_flags),
--> 384                           family=family, match=match or kwarg, **nkw)
    385     # 8<---------------------------------------------------------------
    386 

/myproject/venv/lib/python2.7/site-packages/pyroute2/iproute.pyc in route(self, command, **kwarg)
   1464                                 break
   1465 
-> 1466         ret = self.nlm_request(msg, msg_type=command, msg_flags=flags)
   1467         if match:
   1468             return self._match(match, ret)

/myproject/venv/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.pyc in nlm_request(self, msg, msg_type, msg_flags, terminate, exception_catch, exception_handler)
    771         while True:
    772             try:
--> 773                 return do_try()
    774             except exception_catch as e:
    775                 if exception_handler and not exception_handler(e):

/myproject/venv/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.pyc in do_try()
    750                     msg.reset()
    751                     self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
--> 752                     ret = self.get(msg_seq=msg_seq, terminate=terminate)
    753                     return ret
    754                 except Exception:

/myproject/venv/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.pyc in get(self, bufsize, msg_seq, terminate)
    615                             # The loop is done
    616                             self.backlog_lock.release()
--> 617                             raise msg['header']['error']
    618 
    619                         # If it is the terminator message, say "enough"

NetlinkError: (95, 'Operation not supported')
```

```sh
$ pip freeze | grep pyroute2
pyroute2==0.3.20
```

**Comment by svinota** [comment] 2016-04-12 05:05
The latter is a bug, thanks for reporting. The former is yet an ugly compatibility feature. For now you can just iterate all the table or reference routes with indices — `ipdb.routes[0]`, `ipdb.routes[1]` etc. If you have better ideas, pls tell me — thanks in advance.

NB: IIRC, multiple default routes per se is a deprecated feature, they advise to use multipath routes. Which are another yet poorly implement feature in IPDB, so thanks, I will work with that as well — will try to document, at least.

**Comment by tomislacker** [comment] 2016-04-12 21:43
> The former is yet an ugly compatibility feature.

What is it supporting?  Perhaps if I saw what was dependent on it, I might be able to come up with a suggestion.  Otherwise I just feel like it's a bit misleading if not outwardly incorrect given that the route being returned was the one with the higher of the two metrics.

> IIRC, multiple default routes per se is a deprecated feature, they advise to use multipath routes.

We had discussed back in #171 about the weighted next hops, within a single route, being deprecated due to the removal of the route cache but there's still an applicable use-case for having multiple default routes.  Consider the fail-over scenario:

```sh
$ ip r sh table main
default via 10.0.0.1 dev eth0 proto static metric 100
default via 10.0.0.1 dev wlan0 proto static metric 500
```

With `eth0` became unserviceable, such as loss of ethernet link, the kernel would eventually converge to use `wlan0`.

**Comment by svinota** [comment] 2016-04-12 21:57
Initially, `ipdb.routes['default']` returned a reference to a route, not a list. So I believe there may be a code which depends on it.

So if we change the result to list — it is an API change. Backwards-incompatible, and since the library is in RHEL updates, such a change would be a bad idea.

If we do so it returns a reference if there is one default route, and a list when there are several default routes — it is a mess in types.

So I decided yet to provide a list-like API to routing tables, so one can iterate, filter out default routes and use them. Not an optimal solution yet.

Maybe it would be also good just to pick another keyword to get default routes as a list (with `0 ≤ len() ≤ k`)

**Comment by tomislacker** [comment] 2016-04-13 16:20
Understood, I did neglect to consider other applications depending on the syntax. For at least my use-case, I don't think it's worth it to create a new feature for referencing the default routes.  The only reason I stumbled onto it is because my application requires that there are no default routes in the *"main"* routing table.

As far as the exception bug noted above, would you prefer that I re-file that as a different issue or should I leave it here?

**Comment by svinota** [comment] 2016-04-13 16:51
Just leave it here for now — to keep the discussion open.

The bug with the route deletion will be fixed asap.

**Comment by svinota** [comment] 2016-04-14 21:36
The issue with the default route deletion should be solved now, pls look if it works for you.

At the same time found — and, I hope, solved — a memory leak issue with the route keys.

The `routes['default']` reference still returns one record, yep.

There is some feature (not sure I documented it), that may be useful in your case as well. When route keys are not working well (e.g. when you have two routes with the same destination, like `fe80::/64`, the notation `routes['fe80::/64']` will return also only one route), one can use this syntax: `routes[{'dst': 'fe80::/64', 'oif': 3}]` to match the one that goes via interface with index == 3 — if you do not want to iterate all the table.

**Comment by tomislacker** [comment] 2016-04-15 05:24
The exception is gone but the reference to `{ipdb instance}.routes['default']` is the now the *stale* route despite it being already removed. This is on Python 2.7.10 with a checkout at 195d4296af31239b0cde34f1508f61d9d6541073.

### Setup

```python
from pyroute2 import IPDB
ip = IPDB(mode='implicit')
ip.routes['default']
>>> {'metrics': {}, 'oif': 27, 'type': 1, 'dst_len': 0, 'family': 2, 'proto': 3, 'tos': 0, 'dst': 'default', 'flags': 0, 'ipdb_pri
ority': 0, 'priority': 227, 'scope': 0, 'src_len': 0, 'table': 254, 'multipath': [], 'prefsrc': '172.16.3.40', 'gateway': '172.16.3.25
```

```sh
$ ip r sh table main | grep default
default via 192.168.101.1 dev enp5s0  src 192.168.101.5  metric 202
default via 172.16.3.254 dev tap0 src 172.16.3.42 metric 227
default via 192.168.101.2 dev enp5s0  metric 300
```

### Removal

*I shutdown my tap connection...*

```sh
$ ip r sh table main | grep default
default via 192.168.101.1 dev enp5s0  src 192.168.101.5  metric 202
default via 192.168.101.2 dev enp5s0  metric 300
```

### Result
*From the same IPython session:*

```python
ip.routes['default']
{'metrics': {}, 'oif': 27, 'type': 1, 'dst_len': 0, 'family': 2, 'proto': 3, 'tos': 0, 'dst': 'default', 'flags': 0, 'ipdb_priority': 0, 'priority': 227, 'scope': 0, 'src_len': 0, 'table': 254, 'multipath': [], 'prefsrc': '172.16.3.40', 'gateway': '172.16.3.254', 'ipdb_scope': 'system'}
```

**Comment by svinota** [comment] 2016-04-15 05:29
Bad. Fixing. Sorry for this bustling :)

**Comment by tomislacker** [comment] 2016-04-15 05:33
I appreciate the help sir.  For my solution, I've just implemented some hackiness using `subprocess` calls to enumerate and remove them.  Certainly not ideal, but your library has been immensely useful so I have no regrets.  I'm happy to see I can help at least guide some improvements and I'll try to promise to one day contribute some actual code.

**Comment by svinota** [comment] 2016-04-15 05:49
W/o your contribution a good part of the library functionality wouldn't exist :) Issue reports are important not less than the code contribution.

…

And I reproduced your case, thanks. Fixing.

**Comment by svinota** [comment] 2016-04-15 07:40
The root cause is found. New issue is opened: #232

**Comment by svinota** [comment] 2016-05-19 09:06
The new route key system should be documented asap.

**Closed** 2016-06-26 17:33 UTC
Labels: bug, docs, fixed
