### ISSUE TITLE
IProute.route("add", "fc00::1", oif=1) goes to default IP if no prefix len

### ISSUE THREAD

**Issue by Zashas** [svinota/pyroute2#458] opened 2018-02-18 18:21 UTC
Hi,

I spotted the following bug with pyroute2 from master : 

```py
ipr = IPRoute()
ipr.route('add', dst="fc00::1/16", oif=1)
ipr.route('add', dst="fc00::2", oif=1)
```
will produce from `ip -6 route` : 
```
unreachable fc00::/16 dev lo proto static metric 1024 linkdown error -101 pref medium
unreachable default dev lo proto static metric 1024 linkdown error -101 pref medium
```

The first line works fine. The second bugs, as it changes the IPv6 address "fc00::2" to default. Quite an insidious bug, took me some time to track it down :)

**Comment by svinota** [comment] 2018-03-22 22:43
Thanks! Fixing

**Comment by svinota** [comment] 2018-06-12 10:55
Meanwhile, looks like the issue is fixed for some time :) I'm closing the bug, but feel free to reopen it in the case it returns.

**Closed by svinota** 2018-06-12 10:55 UTC
Labels: bug
