### ISSUE TITLE
IPDB does not kill threads/close sockets on crash

### ISSUE THREAD

**Issue by ctc** [svinota/pyroute2#162] opened 2015-07-22 22:57 UTC
if IPDB crashes on startup the sockets/threads seem to stay open, "close" method will not work as it never returns.

ps -eLf after 4 catched exceptions - there is one main thread, 1 active IPDB thread and 4 "not terminated" ones:

```
root       577     1   577  2    6 22:52 ?        00:00:03 /usr/bin/python3 -u /var/www/scripts/track_firewall.py
root       577     1  1070  0    6 22:52 ?        00:00:00 /usr/bin/python3 -u /var/www/scripts/track_firewall.py
root       577     1  1188  0    6 22:52 ?        00:00:00 /usr/bin/python3 -u /var/www/scripts/track_firewall.py
root       577     1  1202  0    6 22:52 ?        00:00:00 /usr/bin/python3 -u /var/www/scripts/track_firewall.py
root       577     1  1216  0    6 22:52 ?        00:00:00 /usr/bin/python3 -u /var/www/scripts/track_firewall.py
root       577     1  1229  0    6 22:52 ?        00:00:00 /usr/bin/python3 -u /var/www/scripts/track_firewall.py
```

lsof (partial):

```
track_fir 577 root    4r     FIFO    0,8      0t0  11756 pipe
track_fir 577 root    5w     FIFO    0,8      0t0  11756 pipe
track_fir 577 root    6u  netlink             0t0  11757 ROUTE
track_fir 577 root    7r     FIFO    0,8      0t0  12557 pipe
track_fir 577 root    8w     FIFO    0,8      0t0  12557 pipe
track_fir 577 root    9u  netlink             0t0  12559 ROUTE
track_fir 577 root   10r     FIFO    0,8      0t0  10005 pipe
track_fir 577 root   11w     FIFO    0,8      0t0  10005 pipe
track_fir 577 root   12u  netlink             0t0  10008 ROUTE
track_fir 577 root   13r     FIFO    0,8      0t0  12734 pipe
track_fir 577 root   14w     FIFO    0,8      0t0  12734 pipe
track_fir 577 root   15u  netlink             0t0  12738 ROUTE
track_fir 577 root   16r     FIFO    0,8      0t0  10161 pipe
track_fir 577 root   17w     FIFO    0,8      0t0  10161 pipe
track_fir 577 root   18u  netlink             0t0  10166 ROUTE
```

Backtrace in python:

```
  File "/var/www/scripts/track_firewall.py", line 90, in track
    ip = IPDB()
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/__init__.py", line 89, in __new__
    return cls.registry['class'](*argv, **kwarg)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/__init__.py", line 423, in __init__
    self.initdb(nl)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/__init__.py", line 469, in initdb
    routes4 = self.nl.get_routes(family=AF_INET)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/iproute.py", line 383, in get_routes
    routes = self.nlm_request(msg, RTM_GETROUTE, msg_flags)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 782, in nlm_request
    return do_try()
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 761, in do_try
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 671, in get
    data = self.recv(bufsize)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/rtnl/iprsocket.py", line 102, in recv
    data = self._recv(bufsize, flags)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 851, in recv_plugin
    raise data
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 478, in async_recv
    self.buffer_queue.put(self._sock.recv(1024 * 1024))
OSError: [Errno 22] Invalid argument
```

**Comment by svinota** [comment] 2015-07-23 09:16
Thanks, will be fixed until tomorrow.

**Comment by svinota** [comment] 2015-07-27 07:44
Sorry, the simple fix, but took some time.

Pls notice that after the failure the netlink socket can stay open some time until GC will collect the socket object — it's already an internal Python feature.

Could you pls describe also the conditions, when the issue occurs? I'm asking since the failure on the routes request is unusual. Does the exception occur on the current master branch?

**Comment by ctc** [comment] 2015-07-28 00:23
It occurs during boot; rasbian jessie with systemd
I start the netlink script in rc.local

**Comment by ctc** [comment] 2015-07-31 22:34
Exception with current master branch (catched by your code):
```
Traceback (most recent call last):
  File "/var/www/scripts/track_firewall.py", line 90, in track
    ip = IPDB()
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/__init__.py", line 88, in __new__
    return cls.registry['class'](*argv, **kwarg)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/__init__.py", line 420, in __init__
    self.initdb(nl)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/__init__.py", line 475, in initdb
    raise e
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/ipdb/__init__.py", line 466, in initdb
    routes4 = self.nl.get_routes(family=AF_INET)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/iproute.py", line 384, in get_routes
    family=family, match=match or kwarg, **nkw)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/iproute.py", line 1152, in rule
    ret = self.nlm_request(msg, msg_type=command, msg_flags=flags)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 775, in nlm_request
    return do_try()
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 754, in do_try
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 669, in get
    data = self.recv(bufsize)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/rtnl/iprsocket.py", line 106, in recv
    data = self._recv(bufsize, flags)
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 844, in recv_plugin
    raise data
  File "/usr/local/lib/python3.4/dist-packages/pyroute2/netlink/nlsocket.py", line 476, in async_recv
    self.buffer_queue.put(self._sock.recv(1024 * 1024))
OSError: [Errno 22] Invalid argument
```

the threads disappear now and the pipes are closed

**Comment by svinota** [comment] 2015-08-01 08:27
Ok, good. Now I will try to find out why it is failing at all.

**Comment by svinota** [comment] 2018-06-15 15:20
Closing as I can not reproduce and thus debug.

**Closed by svinota** 2018-06-15 15:20 UTC
Labels: bug
