### ISSUE TITLE
RTA_OIF returns wrong index.

### ISSUE THREAD

**Issue by vodik** [svinota/pyroute2#115] opened 2015-03-27 21:24 UTC
Using ipdb.routes and looking at the main route on my machine I'm getting the wrong value in `oif` field:

```python
>>> ipdb.routes['10.10.8.0/21']
{'family': 2,
 'dst_len': 21,
 'proto': 2,
 'oif': 80,
 'dst': '10.10.8.0/21',
 'prefsrc': '10.10.12.163',
 'tos': 0,
 'metrics': {},
 'flags': 0,
 'src_len': 0,
 'table': 254,
 'type': 1,
 'scope': 253}
```

I'm getting 80, but there's no interface on my machine with that id. The correct value should be 4:

```python
>>> ipdb.interfaces[4].ifname
'bridge0'
```

Here's `ip r` output for more information

```
default via 10.10.8.1 dev bridge0  proto static 
10.10.8.0/21 dev bridge0  proto kernel  scope link  src 10.10.8.30
```

**Comment by svinota** [comment] 2015-03-27 21:34
Can not reproduce and can not even imagine, what it can be — not the byte order, not a decoding error.

Will try to play around tomorrow. Could you please send meanwhile:
* `ipdb.nl.get_routes()`
* `ipdb.nl.get_addr()`
* in the shell: `ip route` output

(after removal of any sensitive info, sure)

Also:
* is it reproducible?
* what is the kernel version?

**Comment by vodik** [comment] 2015-03-27 23:47
Will do when I get home. I poked around iproute2 code and it seems like they do some sort of alignment trick that I didn't have enough time to figure out, so there might be something here.

**Comment by vodik** [comment] 2015-03-28 00:15
Okay, so there is a key component to reproducing this issue: first creating a macvlan device and then add an ip.

```python
>>> import pyroute2
>>> ipdb = pyroute2.IPDB()
>>> ipdb.routes['10.10.8.0/21']['oif']
4
>>> with ipdb.create(ifname='macvlan0', kind='macvlan',
                     link=ipdb.interfaces.bridge0) as macvlan:
...    macvlan.up()
>>> ipdb.routes['10.10.8.0/21']['oif']
4
>>> with macvlan:
...    macvlan.add_ip('10.10.12.4', mask=21)
>>> ipdb.routes['10.10.8.0/21']['oif']
82
~~~

Interestingly the 'oif' field keeps going up too. I opened the bug with 80, first time I reproduced this it was 81, now 82.

**Comment by vodik** [comment] 2015-03-28 00:18
And now its really obvious.:

~~~
default via 10.10.8.1 dev bridge0  proto static 
10.10.8.0/21 dev bridge0  proto kernel  scope link  src 10.10.8.30 
10.10.8.0/21 dev macvlan0  proto kernel  scope link  src 10.10.12.4 
~~~

82 is the macvlan! So I think the real bug here is that `routes()` can't return a dictionary, the "key" isn't unique. I thought the `prefsrc` address looked weird in the first request.

And I think the other problem then, why I didn't notice this correctly, is the `ipdb.routes` dictionary seemed to be cached? It didn't recompute itself after the network interface disappeared.

**Comment by vodik** [comment] 2015-03-28 00:23
Yeah, to expand on the above:

~~~
>>> ipdb.routes['10.10.8.0/21']['oif']
82
>>> ipdb.interfaces.macvlan0.remove().commit()
>>> ipdb.routes['10.10.8.0/21']['oif']
82
>>> ipdb.nl.get_routes()
</snip>
>>> ipdb.routes['10.10.8.0/21']['oif']
4
~~~

And the last bit of information you wanted: I'm running 3.19.1-1-ARCH. I'll give you `ipdb.nl.get_routes()` / `ipdb.nl.get_addr()` if you still want (its just a bit long).

**Comment by svinota** [comment] 2015-03-28 09:54
Oh yeah, I've got it.

The only question is what to do now — and not to break the API compatibility. Or just give up and implement in some «right way».

**Comment by vodik** [comment] 2015-03-28 16:55
I don't think you can avoid breaking API, as I see it, there's only two ways this can be implemented:

1. `ipdb.routes` returns a dictionary to a list -> `ipdb.routes['10.10.8.0/21'][0]`
2. `ipdb.routes` returns a list of tuples instead of a dictionary (my preference).

Both breaks things. As I see it, the library is small and new enough that breaking API for correctness is more important than stability. I guess you could always start versioning things if you're worried about breakage (i.e. something maybe like `ipdb = pyroute2.IPDB(future=True)` to enable new stuff).

**Comment by svinota** [comment] 2015-03-28 18:42
+1.

0.3.6 will be released today with old (broken) behaviour of `ipdb.routes`, I schedule it of 0.3.7 — too deep rework of `ipdb.routes` is required.

**Comment by svinota** [comment] 2015-04-04 13:49
@vodik , pls review the changeset e12edfb25ae7cbf7a8e8b92f3b014f7523a3bdd7

I believe it does something you would like.

Still not closing the issue, probably it will require more work.

**Comment by svinota** [comment] 2015-04-04 18:19
A session sample like yours after these changes:

```
In [1]: from pyroute2 import IPDB
In [2]: ip = IPDB()
In [3]: ip.routes['192.168.122.0/24']['oif']
Out[3]: 4
In [4]: with ip.create(ifname='mv0', kind='macvlan', link=ip.interfaces.virbr0) as i:
   ...:     i.up()
   ...:     
In [5]: ip.routes['192.168.122.0/24']['oif']
Out[5]: 4
In [6]: with ip.interfaces.mv0 as i:
   ...:     i.add_ip('192.168.122.99/24')
   ...:     
In [7]: ip.routes['192.168.122.0/24']['oif']
Out[7]: 4
In [8]: ip.routes[{'dst': '192.168.122.0/24', 'prefsrc': '192.168.122.1'}]['oif']
Out[8]: 4
In [9]: ip.routes[{'dst': '192.168.122.0/24', 'prefsrc': '192.168.122.99'}]['oif']
Out[9]: 16216
In [10]: ip.routes.describe({'dst': '192.168.122.0/24', 'prefsrc': '192.168.122.1'})
Out[10]: 
{'index': 2,
 'route': {'family': 2, 'dst_len': 24, 'proto': 2, 'oif': 4, 'dst': '192.168.122.0/24', 'prefsrc': '192.168.122.1', 'tos': 0, 'metrics': {}, 'flags': 0, 'src_len': 0, 'table': 254, 'type': 1, 'scope': 253}}
In [11]: ip.routes.describe({'dst': '192.168.122.0/24', 'prefsrc': '192.168.122.99'})
Out[11]: 
{'index': 8,
 'route': {'type': 1, 'dst_len': 24, 'family': 2, 'proto': 2, 'oif': 16216, 'dst': '192.168.122.0/24', 'table': 254, 'src_len': 0, 'metrics': {}, 'flags': 0, 'tos': 0, 'scope': 253, 'prefsrc': '192.168.122.99'}}
In [12]: ip.routes[2]
Out[12]: {'family': 2, 'dst_len': 24, 'proto': 2, 'oif': 4, 'dst': '192.168.122.0/24', 'prefsrc': '192.168.122.1', 'tos': 0, 'metrics': {}, 'flags': 0, 'src_len': 0, 'table': 254, 'type': 1, 'scope': 253}
In [13]: ip.routes[8]
Out[13]: {'type': 1, 'dst_len': 24, 'family': 2, 'proto': 2, 'oif': 16216, 'dst': '192.168.122.0/24', 'table': 254, 'src_len': 0, 'metrics': {}, 'flags': 0, 'tos': 0, 'scope': 253, 'prefsrc': '192.168.122.99'}
```

**Comment by svinota** [comment] 2015-04-04 18:26
So it is almost fully compatible with the old syntax, except of one case: `'192.168.122.0/24' in ipdb.routes` doesn't work any more, since the routing table now is more like a list, not a dictionary.

But `ipdb.routes['192.168.122.0/24']` also works :) If there are several routes with the same `dst`, the first one will be returned by this notation.

Notation like `ipdb.routes[{'dst': '…', 'prefsrc': '…', 'oif': '…'}]` allows to pick one specific route by keys, not by index.

And remember, that `ipdb.routes[…]` is just a shortcut for `ipdb.routes.tables[254]`, and there are more tables.

**Comment by vodik** [comment] 2015-04-11 19:52
Thanks! I'll look into this.

**Comment by svinota** [comment] 2015-04-27 12:39
0.3.7 is out with the change included.

**Closed by svinota** 2015-04-27 12:39 UTC
Labels: bug, on check
