### ISSUE TITLE
capabilities check leaves a bit of mess on system

### ISSUE THREAD

**Issue by jtluka** [svinota/pyroute2#152] opened 2015-06-12 10:49 UTC
Hi, recent changes that introduced scan of system capabilities (check of bonding, bridging, dummy) leaves the modules being checked loaded. It's not a big deal, however I'm wondering if this could be done differently.

```
modprobe -r bonding
```

```python
#!/usr/bin/python

from pyroute2 import IPRoute

ipr = IPRoute()

lks = ipr.get_links()
```

The code above would leave system with bonding loaded.

```
# lsmod | grep bond
bonding               136616  0
```

Still, this is not really a big deal and is just food for thoughts.

**Comment by svinota** [comment] 2015-06-12 12:41
Yep, that's why it is not a released code yet. My bad, I did it not in a branch.

And your opinion is more than just welcome.

The goals are:
* discover, whether the system is capable of creating required interface types *via netlink* (or we should fallback to the command line utilities)
* discover, if the system has issues with:
 * «ghost» RTM_NEWLINK messages that comes after RTM_DELLINK
 * missing master index on the slave RTM_NEWLINK
 * … [the list is open]
* the capabilities objects *must* be unique per system or namespace due to performance issues, it takes time to collect all the info and the info should not be collected at every IPRSocket instantiation
* the capabilities objects *should* be attached not to config, but IPRSocket objects and should properly represent the target system even if the target system is a remote system.

Alternatives:

* The easiest way would be to guess capabilities by the kernel version — but the backports are unpredictable
* Completely drop the command line fallback support, so if the interface type can not be managed via netlink, it will not be managed
  * A variant: maintain two code branches, «compat» with cli support and «master» with netlink support only

The support of the old systems and the kernel 2.6 is required due to RHEL6.5

…

If you have *any* ideas regarding this, pls write it down. I'm not very glad with the current capabilities implementation as well, since it's in some way destructive.

**Comment by svinota** [comment] 2015-06-12 14:46
Right now I plan to do as follows:

* The capabilities discovery is turned off by default — the library assumes that everything is supported by the netlink protocol and no CLI is required
* The first NetlinkError(errno.ENOTSUPP) turns the particular mechanism to be switched to the cli

The only issue is what to do with «ghost» RTM_NEWLINK messages, but I believe it also can be fixed somehow. So at the release time (the end of June) there will be no destructive tests.

**Comment by jtluka** [comment] 2015-06-12 14:50
what are these ghost messages? right now lnst fails on following:
```
2015-06-12 17:50:35       (localhost)        -   DEBUG: Executing: "ethtool -i pr9372c4dc"
Cannot get driver information: No such device
```
are these the ghost messages?

**Comment by svinota** [comment] 2015-06-12 15:05
No, the message you provided is a bug caused by the capabilities. I added the tag «bug», expect the fix to be provided by this weekend.

…

The ghost messages you can get as follows:

1. launch «ip mon link» in some terminal
2. create a dummy interface --> ip monitor will show RTM_NEWLINK
3. delete the interface --> ip monitor normally will show RTM_DELLINK

But sometimes it should RTM_DELLINK and immediately RTM_NEWLINK:

```
# ip link add test type dummy
(monitor): 
2496: test: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN 
    link/ether 86:2f:70:06:86:a9 brd ff:ff:ff:ff:ff:ff

# ip link del test
(monitor):
Deleted 2496: test: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN 
    link/ether 86:2f:70:06:86:a9 brd ff:ff:ff:ff:ff:ff
2496: test: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN 
    link/ether 86:2f:70:06:86:a9 brd ff:ff:ff:ff:ff:ff
```

Thus any program that relies on these broadcast messages will be sure that the interface immediately gets recreated just after removal. It is a kernel 2.6 «feature», that can be observed on RHEL6.5.

On newer kernels starting from 3.0 there is no such «feature». And since IPDB work with broadcast messages, I have to handle it.

**Comment by jtluka** [comment] 2015-06-12 15:14
Ok, thanks for explanation.

**Comment by svinota** [comment] 2015-06-12 15:30
Just to be clear: this issue the RTM_NEWLINK after the interface removal is not RHEL-specific, but rather kernel 2.6 specific. So I can not, unfortunately, rely on the distro info.

Now I'm trying to find a way to detect this behaviour in some other way.

And really thanks for the feedback, w/o it the capabilities test would be included in the release, and that would be a shame.

**Comment by svinota** [comment] 2015-06-13 10:29
Should be fixed now. Both issues, with modules load (tests now are non-destructive and are performed ad-hoc) and with LNST message (since no test interfaces are created)

**Closed** 2015-06-29 14:26 UTC
Labels: bug, on check, question
