### ISSUE TITLE
IPDB and multipath routes

### ISSUE THREAD

**Issue by crosser** [svinota/pyroute2#436] opened 2017-11-06 16:21 UTC
Checked with todays's master.

When you create a multipath route:
```
# ip -6 route add ::ffff:9.8.7.6/128 table 64 nexthop dev eno1 weight 1 nexthop dev dhcp-s weight 1
```
it is shown as two routes by `ip route list`:
```
# ip -6 route list table 64
::ffff:9.8.7.6 dev eno1  metric 1024  pref medium
::ffff:9.8.7.6 dev dhcp-s  metric 1024  pref medium
```
but IPDB displays only one route:
```
>>> from pyroute2 import IPDB
>>> db=IPDB()
>>> for r in db.routes.tables[64]:
...     print(r)
... 
{'tos': 0, 'flags': 0, 'multipath': (), 'encap': {}, 'table': 64, 'dst_len': 128, 'pref': '00', 'proto': 3, 'ipdb_priority': 0, 'metrics': {}, 'dst': '::ffff:9.8.7.6/128', 'type': 1, 'family': 10, 'oif': 11, 'scope': 0, 'ipdb_scope': 'system', 'src_len': 0, 'priority': 1024}
>>>
```
If you delete one of these routes:
```
# ip -6 route del ::ffff:9.8.7.6/128 table 64 dev eno1
```
the other one is left in the kernel:
```
# ip -6 route list table 64
::ffff:9.8.7.6 dev dhcp-s  metric 1024  pref medium
```
but IPDB thinks that there are no routes:
```
>>> for r in db.routes.tables[64]:
...     print(r)
... 
>>> 
```
until you re-instantiate IPDB. After re-instantiation, it shows one route again. So on both occasions IPDB "sees" less routes than there are in the kernel.

**Comment by svinota** [comment] 2017-11-09 14:52
Yep. I excluded the oif field from the route key (it's only in the NH key for IPv4), and that's the cause. My bad. Now trying to understand how to return it w/o slowing down things again.

**Comment by svinota** [comment] 2018-05-12 15:36
Finally :) it was a tricky fix, this part of IPv6 routing in the kernels has a weird implementation. Some more fixes and the tests will follow, so not closing the issue.

**Comment by crosser** [comment] 2018-05-15 15:54
I do not use this workflow now, so I cannot verify right away. I suggest to close, and in case something shows up it can be reopened.

**Comment by svinota** [comment] 2018-05-15 15:55
Ok, thanks

**Closed** 2018-05-15 15:55 UTC
Labels: bug, fixed
