### ISSUE TITLE
Exception when creating a VRF interface

### ISSUE THREAD

**Issue by tmmorin** [svinota/pyroute2#416] opened 2017-09-01 15:51 UTC
CommitException: target vrf_table is not set  is raised by this kind of piece of code:

```
        with ipdb.create(kind='vrf',
                            ifname=self.vrf_if,
                            vrf_table=self.rt_table,
                            reuse=True) as i:
            i.up()
```

```
  File "/opt/stack/new/networking-bagpipe/networking_bagpipe/bagpipe_bgp/vpn/ipvpn/mpls_linux_dataplane.py", line 91, in __init__
    i.up()
  File "/opt/stack/new/networking-bagpipe/.tox/dsvm-fullstack/local/lib/python2.7/site-packages/pyroute2/ipdb/transactional.py", line 209, in __exit__
    self.commit()
  File "/opt/stack/new/networking-bagpipe/.tox/dsvm-fullstack/local/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 1043, in commit
    raise error
CommitException: target vrf_table is not set
```

(this hits 0.4.20 but was ok in 0.4.17)

**Comment by svinota** [comment] 2017-09-01 16:14
Strange, 'cause nothing has changed in VRF code since 0.4.17.

Ok, let me see.

**Comment by svinota** [comment] 2017-09-01 16:16
I confirm the bug. Thanks a lot!

Fixing now.

**Comment by svinota** [comment] 2017-09-01 16:43
The root couse found, will be fixed tonight.

**Comment by svinota** [comment] 2017-09-01 19:41
Hotfix released. It works in the sense it worked in 0.4.17, but the root cause **not** fixed properly — so will be fixed in the next releases. Not closing the issue yet.

**Comment by tmmorin** [comment] 2017-09-04 08:14
Thanks!
(testing in progress...)

**Comment by tmmorin** [comment] 2017-09-04 11:52
0.4.21 fixes this regression, thanks!

**Comment by tmmorin** [comment] 2017-09-04 11:53
Ah sorry, I closed the issue while you wanted to keep it open...

**Comment by svinota** [comment] 2017-09-08 22:14
Should be fixed for releases starting from 0.5.0

**Closed by svinota** 2017-09-08 22:14 UTC
Labels: bug
