### ISSUE TITLE
Need help with TypeError:

### ISSUE THREAD

**Issue by vinod9987** [svinota/pyroute2#526] opened 2018-07-13 02:24 UTC
Hi All,

I am trying to create a simple Vlan like below but I am running into issues. This might be silly question but I am still learning, so please help.

```
eth1.101  Link encap:Ethernet HWaddr 80:18:44:E0:12:D5  
          inet addr:192.168.1.10  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:252 (252.0 b)
```

I am using below code -

```
from pyroute2 import IPDB
ipdb = IPDB()
link_iface_name = 'eth1'
vlan_iface_name = 'eth1.101'
vlan_iface_id = 101
ipdb = IPDB()
link_iface = ipdb.interfaces[link_iface_name]
with ipdb.create(kind="vlan", ifname=vlan_iface_name, link=link_iface, vlan_id=vlan_iface_id).commit() as i:
        i.add_ip("192.168.1.10", 24)
        i.mtu = 1500
ipdb.release()
```

And I am getting below error -

```
Traceback (most recent call last):
  File "./createVlan.py", line 8, in <module>
    link_iface = ipdb.interfaces[link_iface_name]
  File "/usr/local/lib/python2.7/site-packages/pyroute2/ipdb/main.py", line 1004, in __getattribute__
    obj._register()
  File "/usr/local/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 1154, in _register
    links = self.ipdb.nl.get_links()
  File "/usr/local/lib/python2.7/site-packages/pyroute2/iproute/linux.py", line 237, in get_links
    result.extend(self.link(cmd, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/iproute/linux.py", line 1114, in link
    msg_flags=msg_flags)
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 351, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 832, in nlm_request
    callback=callback):
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 354, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 744, in get
    data = self.recv_ft(bufsize)
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 79, in _p_recv_ft
    data = self._recv_ft(bufsize, flags)
TypeError: recv_ft() takes at most 2 arguments (3 given)
```
I have even tried -

```
Python 2.7.11 (default, Jun 13 2018, 10:30:02) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyroute2 import IPDB
>>> ip = IPDB()
>>> ip.by_name.keys()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pyroute2/ipdb/main.py", line 1004, in __getattribute__
    obj._register()
  File "/usr/local/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 1154, in _register
    links = self.ipdb.nl.get_links()
  File "/usr/local/lib/python2.7/site-packages/pyroute2/iproute/linux.py", line 237, in get_links
    result.extend(self.link(cmd, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/iproute/linux.py", line 1114, in link
    msg_flags=msg_flags)
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 351, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 832, in nlm_request
    callback=callback):
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 354, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 744, in get
    data = self.recv_ft(bufsize)
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 79, in _p_recv_ft
    data = self._recv_ft(bufsize, flags)
TypeError: recv_ft() takes at most 2 arguments (3 given)
>>> 
```

I am using freshly installed Centos 6.9 on kernel 2.6.32-696.30.1.el6.x86_64. Any help is truly appreciated.

Thanks,
Vinod

**Comment by svinota** [comment] 2018-07-13 06:08
Ough! Which pyroute2 version do you use?

**Comment by svinota** [comment] 2018-07-13 06:17
Got it. It's a bug on the library, sorry. Fixing.

**Comment by svinota** [comment] 2018-07-13 06:20
The bug appears only on old kernels < 3.3.0, caused by the internal library API. Will be fixed tonight.

**Comment by vinod9987** [comment] 2018-07-13 06:49
Thanks for looking into this Peter.
I am using Version: 0.5.2

Regards,
Vinod

**Comment by svinota** [comment] 2018-07-14 20:31
Tried to make a simple quick-fix, but the issue is a bit more complicated. I'm trying to fix it until the next weekend. Sorry for the delay.

**Comment by vinod9987** [comment] 2018-09-19 07:44
Peter any way forward you found for this issue?

Thanks,
Vinod

**Comment by svinota** [comment] 2018-09-27 13:06
@vinod9987 can you check — if it's working now? I started to fix but then suddenly didn't do the last step, sorry. There it is (I hope).

**Closed** 2022-05-13 16:31 UTC
Labels: bug
