### ISSUE TITLE
TypeError: recv_ft()

### ISSUE THREAD

**Issue by vinod9987** [svinota/pyroute2#525] opened 2018-07-13 01:58 UTC
Hi all,

I am getting below error, not able to figure out why. Any help is appreciated. 
```
Python 2.7.11 (default, Jun 13 2018, 10:30:02) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-18)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyroute2 import IPDB
>>> ip = IPDB()
>>> ip.by_name.keys()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pyroute2/ipdb/main.py", line 1004, in __getattribute__
    obj._register()
  File "/usr/local/lib/python2.7/site-packages/pyroute2/ipdb/interfaces.py", line 1154, in _register
    links = self.ipdb.nl.get_links()
  File "/usr/local/lib/python2.7/site-packages/pyroute2/iproute/linux.py", line 237, in get_links
    result.extend(self.link(cmd, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/iproute/linux.py", line 1114, in link
    msg_flags=msg_flags)
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 351, in nlm_request
    return tuple(self._genlm_request(*argv, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 832, in nlm_request
    callback=callback):
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 354, in get
    return tuple(self._genlm_get(*argv, **kwarg))
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/nlsocket.py", line 744, in get
    data = self.recv_ft(bufsize)
  File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/rtnl/iprsocket.py", line 79, in _p_recv_ft
    data = self._recv_ft(bufsize, flags)
TypeError: recv_ft() takes at most 2 arguments (3 given)
```

I am using freshly installed Centos 6.9 kernel 2.6.32-696.30.1.el6.x86_64

Thanks,
Vinod

**Comment by svinota** [comment] 2018-07-13 06:14
Closing that as a duplicate of https://github.com/svinota/pyroute2/issues/526

**Closed by svinota** 2018-07-13 06:14 UTC
