### ISSUE TITLE
NetNS objects leak

### ISSUE THREAD

**Issue by nickhuber** [svinota/pyroute2#400] opened 2017-07-28 17:06 UTC
the NetNS object doesn't clean up all of its resources on close() leading to some memory and fd leaks.

This is pretty easily replicated:

```
import pyroute2
for _ in range(1000):
    n = pyroute2.NetNS('testing')
    n.close()
```

On my system if I run that again I'll get an error about too many open files

lsof shows many open pipes:

```
...
python3 7044 root    8r  FIFO               0,11       0t0 286015306 pipe
python3 7044 root    9r  FIFO               0,11       0t0 286085453 pipe
python3 7044 root   10r  FIFO               0,11       0t0 286085459 pipe
python3 7044 root   11r  FIFO               0,11       0t0 286085465 pipe
python3 7044 root   12r  FIFO               0,11       0t0 286084620 pipe
python3 7044 root   13r  FIFO               0,11       0t0 286089223 pipe
python3 7044 root   14r  FIFO               0,11       0t0 286085471 pipe
python3 7044 root   15r  FIFO               0,11       0t0 286087185 pipe
python3 7044 root   16r  FIFO               0,11       0t0 286087191 pipe
python3 7044 root   17r  FIFO               0,11       0t0 286086262 pipe
...
```

also if you monitor the memory usage of the interpreter it grows with each created NetNS object

**Comment by svinota** [comment] 2017-07-28 17:20
A bit strange, as it passes the test: https://github.com/svinota/pyroute2/blob/master/tests/general/test_stress.py#L87

It may mean also, that the test doesn't catch the bug — that's evern worse.

Thanks a lot for the feedback. Could you please specify also the library version you use?

**Comment by nickhuber** [comment] 2017-07-28 17:22
I'm using 0.4.18 of pyroute2 from pypi

**Comment by svinota** [comment] 2017-07-28 17:23
That's bad.

Thanks again! Investigating.

**Comment by svinota** [comment] 2017-07-28 19:01
Can not confirm the pipes leakage with the code provided neither with Python3, nor with Python2 — checked with `/proc/<pid>/fd/`. Both on 0.4.18 and on the master branch.

Could you pls confirm that you can observe leaked pipes in `/proc/<pid>/fd/` with the code provided? And what the Python3 version is used?

Probably, the leakage was caused by some other condition, so I continue the investigation.

With the memory it's a bit more complicated issue, I will report here a bit later.

**Comment by nickhuber** [comment] 2017-07-28 20:09
```
ls -al /proc/12490/fd
total 0
dr-x------ 2 root root  0 Jul 28 13:07 .
dr-xr-xr-x 9 root root  0 Jul 28 13:07 ..
lrwx------ 1 root root 64 Jul 28 13:07 0 -> /dev/pts/50
lrwx------ 1 root root 64 Jul 28 13:07 1 -> /dev/pts/50
lr-x------ 1 root root 64 Jul 28 13:08 10 -> pipe:[290232880]
lr-x------ 1 root root 64 Jul 28 13:08 100 -> pipe:[290223041]
lr-x------ 1 root root 64 Jul 28 13:08 1000 -> pipe:[290240448]
lr-x------ 1 root root 64 Jul 28 13:08 1001 -> pipe:[290240833]
lr-x------ 1 root root 64 Jul 28 13:08 1002 -> pipe:[290182865]
lr-x------ 1 root root 64 Jul 28 13:08 1003 -> pipe:[290240839]
lr-x------ 1 root root 64 Jul 28 13:08 1004 -> pipe:[290240456]
lr-x------ 1 root root 64 Jul 28 13:08 1005 -> pipe:[290240462]
lr-x------ 1 root root 64 Jul 28 13:08 1006 -> pipe:[290240468]
lr-x------ 1 root root 64 Jul 28 13:08 101 -> pipe:[290233503]
lr-x------ 1 root root 64 Jul 28 13:08 102 -> pipe:[290208348]
lr-x------ 1 root root 64 Jul 28 13:08 103 -> pipe:[290182608]
```

it continues on for quite a while after that. I'm using python 3.6.2

**Comment by roolebo** [comment] 2017-07-28 20:20
We have to bump upper version for Python leak workaround. The fix is not
applied for Python 3.6+ as of now
пт, 28 июля 2017 г. в 23:09, Nick Huber <notifications@github.com>:

**Comment by svinota** [comment] 2017-07-28 20:35
Interesting.

```
$ python3 -V
Python 3.5.3
```
… and the bug isn't reproduced.

I'll try 3.6.x versions.

**Comment by nickhuber** [comment] 2017-07-28 20:46
Can confirm the pipes don't leak on python3.5, but the memory usage still increases.

I have seen the memory usage increase in some of our production uses of this (on python 3.5.1) and once memory usage was exhausted it started to leak pipes as well. That scenario might be a bit contrived since memory was already exhausted at that point.

The initial problem of memory leaking is still a concern

**Comment by svinota** [comment] 2017-07-28 22:07
Meanwhile, I confirm the memory leak on all the Python versions. Tracking the cause.

**Comment by svinota** [comment] 2017-07-28 22:19
@roolebo I remove the constraint right now. Antoine Pitrou simply refuses to even see the issue, and I don't believe it will be solved ever.

**Comment by svinota** [comment] 2017-07-28 22:25
@nickhuber pushed the pipe leak workaround into the master. If it is possible to check if it helps, that would be really great (the memory leak is still being investigated). Thanks!

**Comment by nickhuber** [comment] 2017-07-28 22:31
@svinota this change prevents the runtime leakage of pipes on python 3.6 for me

**Comment by svinota** [comment] 2017-09-08 22:15
As the Python team won't fix that, leaving the workaround in place for all the Python 3 releases.

**Closed by svinota** 2017-09-08 22:15 UTC
Labels: bug, deps bug
