### ISSUE TITLE
NetlinkError: (9, 'Bad file descriptor') when moving an interface from one netns to another

### ISSUE THREAD

**Issue by Callum027** [svinota/pyroute2#217] opened 2016-02-18 04:27 UTC
Got two test scripts for this one, because I was intending to connect two network namespaces using veth interfaces. [This first test script](https://github.com/svinota/pyroute2/files/135636/test.py.txt) attempts to do this, while [the second](https://github.com/svinota/pyroute2/files/135654/test2.py.txt) creates a GRE interface in one namespace and attempts to move it over.

You can change the operation of the test scripts to create the interfaces on the root namespace by simply changing the `foo_ipdb` variable to create a blank `IPDB` object, rather than using `IPDB(nl=foo_netns)`.

Script 1, expected output:

    root@ubuntu:~# ./test.py
    setting up NetNS for foo
    setting up IPDB for foo
    setting up NetNS for bar
    setting up IPDB for foo
    creating testveth0 on foo
    committing to foo_ipdb
    fetching testveth1 from foo
    setting testveth1 netns to bar
    committing to foo_ipdb
    fetching testveth1 from bar
    adding 172.16.0.1/24 to testveth0 on foo
    committing to foo_ipdb
    bringing up testveth0 on foo
    committing to foo_ipdb
    bringing up testveth1 on bar
    committing to bar_ipdb
    bringing down testveth0 on foo
    committing to foo_ipdb
    bringing down testveth1 on bar
    committing to bar_ipdb
    removing testveth0 on foo
    committing to foo_ipdb
    running testveth0 non-existence assert in foo_ipdb
    running testveth1 non-existence assert in bar_ipdb
    closing IPDB for foo
    releasing NetNS for foo
    removing netns testveth0
    releasing IPDB for foo
    closing NetNS for bar
    removing netns bar

Script 1, actual output:

    root@ubuntu:~# ./test.py
    setting up NetNS for foo
    setting up IPDB for foo
    setting up NetNS for bar
    setting up IPDB for foo
    creating testveth0 on foo
    committing to foo_ipdb
    fetching testveth1 from foo
    setting testveth1 netns to bar
    committing to foo_ipdb
    Traceback (most recent call last):
      File "./test.py", line 30, in <module>
        foo_ipdb.commit()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/__init__.py", line 895, in commit
        target.commit(transaction=tx, rollback=rollback)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/interface.py", line 818, in commit
        raise error
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/interface.py", line 640, in commit
        self.nl.link('set', **request)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/iproute.py", line 704, in link
        exception_handler=update_caps)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 783, in nlm_request
        return do_try()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 762, in do_try
        ret = self.get(msg_seq=msg_seq, terminate=terminate)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 618, in get
        raise msg['header']['error']
    pyroute2.netlink.NetlinkError: (9, 'Bad file descriptor')

Script 2, expected output:

    root@ubuntu:~# ./test2.py
    setting up NetNS for foo
    setting up IPDB for foo
    setting up NetNS for bar
    setting up IPDB for foo
    creating testgre0 on foo
    committing to foo_ipdb
    setting testgre0 netns to bar
    committing to foo_ipdb
    fetching testgre0 from bar
    adding 172.16.0.1/24 to testgre0 on bar
    committing to bar_ipdb
    bringing up testgre0 on bar
    committing to bar_ipdb
    bringing down testvgre0 on bar
    committing to bar_ipdb
    removing testgre0 on bar
    committing to bar_ipdb
    running testgre0 non-existence assert in bar_ipdb
    closing IPDB for foo
    releasing NetNS for foo
    removing netns foo
    releasing IPDB for foo
    closing NetNS for bar
    removing netns bar

Script 2, actual output:

    root@ubuntu:~# ./test2.py
    setting up NetNS for foo
    setting up IPDB for foo
    setting up NetNS for bar
    setting up IPDB for foo
    creating testgre0 on foo
    committing to foo_ipdb
    setting testgre0 netns to bar
    committing to foo_ipdb
    Traceback (most recent call last):
      File "./test2.py", line 35, in <module>
        foo_ipdb.commit()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/__init__.py", line 895, in commit
        target.commit(transaction=tx, rollback=rollback)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/interface.py", line 818, in commit
        raise error
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/interface.py", line 640, in commit
        self.nl.link('set', **request)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/iproute.py", line 704, in link
        exception_handler=update_caps)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 783, in nlm_request
        return do_try()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 762, in do_try
        ret = self.get(msg_seq=msg_seq, terminate=terminate)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 618, in get
        raise msg['header']['error']
    pyroute2.netlink.NetlinkError: (9, 'Bad file descriptor')

EDIT: Also, out of curiosity, here is the output from manually creating and moving a veth interface across network namespaces:

    root@ubuntu:~# ip netns add foo

    root@ubuntu:~# ip netns exec foo ip link add testveth0 type veth peer name testveth1

    root@ubuntu:~# ip netns add bar

    root@ubuntu:~# ip netns exec foo ip link set testveth1 netns bar

    root@ubuntu:~# ip netns exec foo ip link list
    1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default 
        link/gre 0.0.0.0 brd 0.0.0.0
    3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    5: testveth0@if4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether f6:91:8a:31:ef:7c brd ff:ff:ff:ff:ff:ff

    root@ubuntu:~# ip netns exec bar ip link list
    1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default 
        link/gre 0.0.0.0 brd 0.0.0.0
    3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    4: testveth1@if5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether f6:6a:6b:9b:e0:de brd ff:ff:ff:ff:ff:ff

**Comment by svinota** [comment] 2016-02-19 09:03
reproduced, investigating

**Comment by svinota** [comment] 2016-02-19 11:38
Ok, the error source found. To fix the root cause one should seriously change the communication protocol between the client part of the library working in the host system and the server part working in a netns.

Thanks for bringing that up. The fix will be available on the next Monday.

**Comment by svinota** [comment] 2016-02-21 23:04
First attempt to fix. May be not stable yet, fd leaks possible. Some bugs introduced, fixing now. But you can already try to preview.

**Comment by Callum027** [comment] 2016-02-22 00:05
With the latest revision, I get errors and the scripts quit, but the move operations actually complete, if you look at the calls to `ip link list` after the test script runs.

Script 1:

    root@ubuntu:~# ./test1.py
    setting up NetNS for foo
    setting up IPDB for foo
    setting up NetNS for bar
    setting up IPDB for foo
    creating testveth0 on foo
    committing to foo_ipdb
    fetching testveth1 from foo
    setting testveth1 netns to bar
    committing to foo_ipdb
    fetching testveth1 from bar
    adding 172.16.0.1/24 to testveth0 on foo
    committing to foo_ipdb
    bringing up testveth0 on foo
    committing to foo_ipdb
    bringing up testveth1 on bar
    committing to bar_ipdb
    bringing down testveth0 on foo
    committing to foo_ipdb
    bringing down testveth1 on bar
    committing to bar_ipdb
    removing testveth0 on foo
    committing to foo_ipdb
    Traceback (most recent call last):
      File "./test1.py", line 62, in <module>
        foo_ipdb.commit()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/__init__.py", line 895, in commit
        target.commit(transaction=tx, rollback=rollback)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/interface.py", line 818, in commit
        raise error
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/interface.py", line 752, in commit
        self.nl.link('delete', **self)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/iproute.py", line 704, in link
        exception_handler=update_caps)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 773, in nlm_request
        return do_try()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 751, in do_try
        self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 532, in put
        self.marshall(msg, addr)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/remote/__init__.py", line 252, in _marshall
        pickle.dumps(msg.dump()),
    _pickle.PicklingError: Can't pickle <class '_thread.lock'>: attribute lookup lock on _thread failed

    root@ubuntu:~# ip netns exec foo ip link list
    1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default 
        link/gre 0.0.0.0 brd 0.0.0.0
    3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    5: testveth0@if4: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
        link/ether 56:c4:94:45:2b:c8 brd ff:ff:ff:ff:ff:ff
    root@ubuntu:~# ip netns exec bar ip link list
    1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default 
        link/gre 0.0.0.0 brd 0.0.0.0
    3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    4: testveth1@if5: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
        link/ether 46:fb:fb:e9:d3:e4 brd ff:ff:ff:ff:ff:ff

Script 2:

    root@ubuntu:~# ./test2.py
    setting up NetNS for foo
    setting up IPDB for foo
    setting up NetNS for bar
    setting up IPDB for foo
    creating testgre0 on foo
    committing to foo_ipdb
    setting testgre0 netns to bar
    committing to foo_ipdb
    fetching testgre0 from bar
    adding 172.16.0.1/24 to testgre0 on bar
    committing to bar_ipdb
    bringing up testgre0 on bar
    committing to bar_ipdb
    bringing down testvgre0 on bar
    committing to bar_ipdb
    removing testgre0 on bar
    committing to bar_ipdb
    Traceback (most recent call last):
      File "./test1", line 58, in <module>
        bar_ipdb.commit()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/__init__.py", line 895, in commit
        target.commit(transaction=tx, rollback=rollback)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/interface.py", line 818, in commit
        raise error
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/ipdb/interface.py", line 752, in commit
        self.nl.link('delete', **self)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/iproute.py", line 704, in link
        exception_handler=update_caps)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 773, in nlm_request
        return do_try()
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 751, in do_try
        self.put(msg, msg_type, msg_flags, msg_seq=msg_seq)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/netlink/nlsocket.py", line 532, in put
        self.marshall(msg, addr)
      File "/opt/catalyst/venv/l3overlay/lib/python3.4/pyroute2/remote/__init__.py", line 252, in _marshall
        pickle.dumps(msg.dump()),
    _pickle.PicklingError: Can't pickle <class '_thread.lock'>: attribute lookup lock on _thread failed

    root@ubuntu:~# ip netns exec bar ip link list
    1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN mode DEFAULT group default 
        link/gre 0.0.0.0 brd 0.0.0.0
    3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN mode DEFAULT group default qlen 1000
        link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    4: testgre0@NONE: <POINTOPOINT,NOARP> mtu 1476 qdisc noqueue state DOWN mode DEFAULT group default 
        link/gre 192.0.2.0 peer 192.0.2.1

**Comment by svinota** [comment] 2016-02-22 00:07
Yep. Continuing. Sorry for the delay.

**Comment by svinota** [comment] 2016-02-22 00:37
The issue with locks fixed, scripts work, but the work on the issue continues. The final version will be released the next Friday, 26.02, after all the tests and code cleanup.

**Comment by Callum027** [comment] 2016-02-22 02:55
Cool, thanks for getting onto this so quickly. It now works properly on my end. :)

**Comment by svinota** [comment] 2016-02-22 06:28
Good. Pls notice that it may be not stable yet, more related commits may follow. So I'm not closing the bug record yet.

**Comment by svinota** [comment] 2016-02-23 14:40
Tests implemented. Closing the record.

**Closed by svinota** 2016-02-23 14:40 UTC
Labels: bug, fixed
