### ISSUE TITLE
netlink attribute payload byteorder issue on bigendian machines

### ISSUE THREAD

**Issue by sm00th** [svinota/pyroute2#128] opened 2015-04-27 13:37 UTC
There seems to be some issue with nla messages on big-endian machines. When running a simple script like this (pyroute2 0.3.6):
```python
from pyroute2 import IPRSocket

ip = IPRSocket()
ip.bind()
while 1:
  print "%s" % ip.get()
ip.close()
```
I occasionally get traces like the one below:
```
WARNING:root:decoding NDA_DST
WARNING:root:Traceback (most recent call last):
  File "build/bdist.linux-ppc64/egg/pyroute2/netlink/__init__.py", line 1084, in decode_nlas
    nla.decode()
  File "build/bdist.linux-ppc64/egg/pyroute2/netlink/__init__.py", line 1215, in decode
    family = self.family_map[self.parent['family']]
KeyError: 33554432
```
This happens when fmt in pyrote2.netlink.nlmsg_base.decode() is 'i', I've also looked at raw data in that message and it is `0x02 0x00 0x00 0x00`, so a little-endian 2.
It looks like pyroute2 expects NLAs to be in host's byte-order, but at least according to [this](http://linux-development-for-fresher.blogspot.cz/2012/05/understanding-netlink-socket.html) it is possible for payload to be in network byte-order.

**Comment by svinota** [comment] 2015-04-27 14:43
Yep. Thanks for the report, fixing.

**Comment by svinota** [comment] 2015-04-27 20:46
Could you please specify also:

* CPU architecture
* kernel version as per `uname -r`

Trying to get the error on my hardware, but still w/o success. But it's definitively an endianness issue, yep.

**Comment by sm00th** [comment] 2015-04-27 21:30
I got this on RHEL6/RHEL7, so 2.6.32-504.el6/3.10.0-229.el7 ppc64 series repspectively. CentOS kernels should yield the same results.

**Comment by svinota** [comment] 2015-04-27 22:47
Ok, thanks.

I believe it should be a pyroute2 issue, so it should be reproducible on Debian kernels as well — just good to know what the flavour to look on.

**Comment by svinota** [comment] 2015-04-27 22:58
Though reading the kernel sources I still do not get how it's possible: I would rather expect `ndm->ndm_family` in the host order always, not sometimes. Looks like I'm missing something.

Will try to get some ppc node to play with.

Does other stuff works somehow, like `IPRoute.get_links()`, `IPRoute.get_addr()` etc.? Probably it should fail also — that would be easier to debug, if everything fails :)

**Comment by sm00th** [comment] 2015-04-28 08:52
Other stuff seems to work just fine, I initially hit those traces while running LNST, it does a lot of stuff and everything seemed to be in order, all tests passed, just a bunch of traces.
It might help to introduce some network activity, e.g. ping something while running IPRSocket.get() in a loop to reproduce this. It is not reproducible off the bat, but I can reproduce it within 5 minutes or so while pinging hosts within local network.

**Comment by svinota** [comment] 2015-04-28 09:15
Bad. I hoped it will not work at all — in that case I would now where to look.

Installing several big-endian MIPS VMs, will try to reproduce it today.

Actually, really thanks for heads-up, it's a good idea to regularly run tests on big-endian platforms also (now I do it on 32/64 little-endian only, x86 and ARM). Maybe, I'm to integrate LNST into pyroute2 CI testing — if I already run it on several nodes, so why not to engage something already doing that.

**Comment by svinota** [comment] 2015-04-28 15:14
Reproduced on big-endian MIPS.

The reason for the bug in pyroute2 was that the family field in the kernel's ndmsg definition is not `int32`, but `uint8` + 3 bytes pad. No idea, why it was `int32` in `pyroute2` definition :)

As a temporary solution the field is forced to be covered by a little-endian int. It works, but it's a hack.

Please don't close the issue. Instead of the endianness hack the issue must be fixed with a real definition (`uint8` + 3 bytes pad), but right now the fix has a side-effect breaking `NetNS`.

**Comment by svinota** [comment] 2015-04-28 16:12
Looks like all the CI tests pass. Pls excuse for the delay.

Please check if it works for you, and if it does, close the issue. Thanks!

**Comment by sm00th** [comment] 2015-04-29 07:47
I ran through a bunch of tests and can't everything looks fine, so the issue seems to be resolved. Thank you.

**Comment by svinota** [comment] 2015-04-29 08:17
Thanks!

**Closed by svinota** 2015-04-29 08:17 UTC
Labels: bug, on check
