### ISSUE TITLE
[Question] calling IPDB() sometimes fails.

### ISSUE THREAD

**Issue by takaomag** [svinota/pyroute2#126] opened 2015-04-25 07:11 UTC
Hi,

I have a quetion about IPDB. I prepared the following test code for simplicity.

* pyroute version: 0.3.6

```
from pyroute2 import IPDB

def get_routes():
    with IPDB() as ipdb:
        routes = ipdb.routes
        result = {
            dst: routes[dst].dump()
            for dst in routes.keys()
        }

for i in range(10):
    get_routes()
    print('{}: OK'.format(i))
```

There are two environments.

### On an Archlinux docker container on CoreOS
* kernel version: 3.19.0 (host)
* iproute2 version: iproute2-ss150210 (container)
* python version: 3.4.3 (container)

Launch my docker container on CoreOS by
`docker run -it --rm --net host --pid host --privileged -v /run/netns:/run/netns {my_container} /bin/bash`
and call python3 in the container
* result: All passed.

### On an Archlinux docker container (same image as above) on CentOS 7
* CentOS version: 7.1.1503
* kernel version: 4.0.0-1.el7.elrepo.x86_64 (host)
* iproute2 version: iproute2-ss150210 (same as above because of same image)
* python version: 3.4.3 (same as above because of same image)

Launch my docker container on CentOS by
`docker run -it --rm --net host --pid host --privileged -v /run/netns:/run/netns {my_container} /bin/bash`
and call python3 in the container

* result: OSError [errno 22]
```
0: OK
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "<stdin>", line 2, in get_routes
  File "/opt/magonet1/lib/python3.4/site-packages/pyroute2/__init__.py", line 79, in __call__
    return self.proxy['constructor'](*argv, **kwarg)
  File "/opt/magonet1/lib/python3.4/site-packages/pyroute2/ipdb/__init__.py", line 404, in __init__
    self.initdb(nl)
  File "/opt/magonet1/lib/python3.4/site-packages/pyroute2/ipdb/__init__.py", line 427, in initdb
    self.nl.bind(async=True)
  File "/opt/magonet1/lib/python3.4/site-packages/pyroute2/netlink/rtnl/__init__.py", line 233, in bind
    super(IPRSocketMixin, self).bind(groups, async=async)
  File "/opt/magonet1/lib/python3.4/site-packages/pyroute2/netlink/nlsocket.py", line 462, in bind
    super(NetlinkMixin, self).bind((self.epid, self.groups))
OSError: [Errno 22] Invalid argument
```

It seems an OSError raised after a few (1, 2 or 3) success. This may occur only on my environment. But is there any way or hint to work around it ?

**Comment by takaomag** [comment] 2015-04-25 07:30
I have tested the above test code on the CentOS 7 with os-default python2, which means "no docker".
But same error occurs.

**Comment by svinota** [comment] 2015-04-25 12:05
Really thanks for the detailed information!

The issue definitively needs a fix, started to look into.

**Comment by takaomag** [comment] 2015-04-25 13:00
I'm sorry, it seems the new kernel is the cause.

As above, I tested it on the kernel 4.0.0-1.el7.elrepo.x86_64, since I want to use some new kernel futures.

After downgraded it to CentOS's default (3.10.0-229.1.2.el7.x86_64), it seems to work well.
I'm not sure the reason, but the kernel 4 may have some modifications on NetLink behavior, or have some bug. Anyway, I'm sorry.

Can I close this issue ?

**Comment by svinota** [comment] 2015-04-25 13:03
Nope.

I'm already trying to investigate what's wrong with the new kernel and make a workaround, if it is possible.

**Comment by takaomag** [comment] 2015-04-25 13:10
Thanks.
The cause may be one of the followings,

1. Kernel 4.0.0-1.el7.elrepo.x86_64 has a bug.
2. Some utils around the kernel (including iproute2) have to be upgraded to latest vesion also.
3. Kernel 4.0.0-1.el7.elrepo.x86_64 has modified NetLink behavior.

**Comment by svinota** [comment] 2015-04-25 13:16
pyroute2 uses external utilities only as a fallback on old kernels (e.g. RHEL6.5) and only for some operations (e.g. bridge management), so iproute2 should not be a reason in any case.

I think there can be some issue with RTNL on kernel 4.0, and that's why I'm playing around now: it's better to get ready until it's not too late :)

**Comment by svinota** [comment] 2015-04-25 14:24
The fix for IPDB will be available tonight.

No fix will be done for IPRoute — after a failed `bind()`, no successful `bind()` call can be done on the same socket object.

IPDB just re-creates underlying IPRoute if it gets broken, so IPDB will be fixed.

**Comment by takaomag** [comment] 2015-04-25 14:32
Great !
I will be able to use the kernel 4 for some futures.

**Comment by svinota** [comment] 2015-04-25 17:12
Moved the netlink port scan logic from `NetlinkSocket` to `IPDB`.

If you are interested, whether it becomes engaged during the `IPDB` init, you can turn on the debug logging:

```
import logging
from pyroute2 import IPDB

root = logging.getLogger()
root.setLevel(logging.DEBUG)


def get_routes():
    with IPDB() as ipdb:
        routes = ipdb.routes
        result = {
            dst: routes[dst].dump()
            for dst in routes.keys()
        }

for i in range(10):
    get_routes()
    print('{}: OK'.format(i))
```

The issue description:

* Kernel < 4.0 allows multiple `bind()` call until the first success
* Kernel >= 4.0 doesn't — the first failed `bind()` makes the socket useless

This excludes the netlink «port» scan functionality from the socket level. So if the kernel doesn't support the netlink «port» reuse, this scan can be done only by creating new socket objects.

With the issue you reported I already managed to fix a netlink port leakage that existed in `NetlinkSocket`, thanks.

Please, check if the solution works for you. And thanks again for the report.

**Comment by svinota** [comment] 2015-04-25 23:08
Pls keep in mind also: all this means that there is a limited amount of `NetlinkSocket` (the lowes API level) objects, for which the `bind()` call can be done successfully.

Thus, for long-running processes it is better to keep a permanent IPDB object or set of objects.

It is valid for all pyroute2 versions on any kernel. Previous behaviour masked this issue with a hidden port leakage. The simplest demo code:
```
from pyroute2 import IPRoute

for x in range(2000):
    if x % 10 == 0:
        print(x)
    ip = IPRoute()
    ip.bind()
    ip.close()
```
It will fail after 1024 `bind()` calls anyway, even on 3th kernels.

**Comment by svinota** [comment] 2015-04-26 00:39
Just found, what caused the issue with the port reuse.

The root cause was that Python doesn't close the socket when you call `socket.close()`. The socket gets closed only when it gets garbage collected.

Trying to fix the `NetlinkSocket` object now. If will succeed, the issue will be completely solved.

**Comment by takaomag** [comment] 2015-04-26 01:13
Thanks.

I tried the new code (30 minites ago). It works !

> Thus, for long-running processes it is better to keep a permanent IPDB object or set of objects.

I have a long-running process which uses pyroute2. To clalify it, do I have to do as follows ?

### For Single-thread environment.

```
from pyroute2 import IPDB

class SimpleManager(object):

    def __init__(self, ipdb_kwargs=None):
        self._ipdb_kwargs = ipdb_kwargs or {}

    @property
    def ipdb(self):
        try:
            return self._ipdb
        except AttributeError:
            ipdb = self._ipdb = IPDB(**self._ipdb_kwargs)
            return ipdb

    def get_routes(self, ipdb_kwargs=None):
        with self.ipdb as ipdb:
            routes = ipdb.routes
            return {
                dst: routes[dst].dump()
                for dst in routes.keys()
            }

m = SimpleManager()
for i in range(10):
    r = m.get_routes()
    print('{}: OK'.format(i))
```

#### For multi-threads environment
In case that many child threads use IPDB.
```
from pyroute2 import IPDB
import threading
from Queue import LifoQueue

class ThreadSafeManager(object):

    def __init__(self, num_of_ipdb=3, ipdb_kwargs=None):
        q = self._ipdb_q = LifoQueue(maxsize=num_of_ipdb)
        for i in range(num_of_ipdb):
            q.put(IPDB(**(ipdb_kwargs or {})))

    def get_routes(self, ipdb_kwargs=None):
        ipdb = self._ipdb_q.get()
        try:
            with ipdb:
                routes = ipdb.routes
                return {
                    dst: routes[dst].dump()
                    for dst in routes.keys()
                }
        finally:
            self._ipdb_q.put(ipdb)

m = ThreadSafeManager()
threads = []
for i in range(10):
    t=threading.Thread(target=m.get_routes)
    t.start()
    threads.append(t)

for t in threads:
    t.join()
```

**Comment by takaomag** [comment] 2015-04-26 01:30
> The root cause was that Python doesn't close the socket when you call socket.close(). The socket gets closed only when it gets garbage collected.

Python may not close a socket immediately after close() is called. But will close immediately after shutdown() is called ([python doc](https://docs.python.org/3/library/socket.html)), though I don't know shutdown() is always safe.

**Comment by svinota** [comment] 2015-04-26 01:37
Unfortunately, shutdown() doesn't work on these sockets at all. I'm trying to test the workaround that would not be too ugly, we'll see.

Roughly speaking, yes, the possible solution to have a limited number of `IPDB` instances could be like that you posted. One addition: I tried to make `IPDB` thread-safe, so it should work across threads as well. If nothing got broken so far :)

**Comment by svinota** [comment] 2015-04-26 02:03
Started new branch: https://github.com/svinota/pyroute2/tree/socket_close

Playing around the issue there.

So far it is not as good as I would expect it, but trying. Will continue on Sunday.

**Comment by takaomag** [comment] 2015-04-26 03:03
Thank you so much.

For now, as a temporary solution, I use a Queue which has a few number of IPDBs for multi-threads environment.

**Comment by svinota** [comment] 2015-04-26 13:49
I managed to fix it without performance regression. At least, without a significant one.

Polishing all the details — the solution still conflicts with asynchronous mode in IPRoute — but on Monday you can expect the fix to be ready.

Also postponing 0.3.7 to include the fix.

**Comment by svinota** [comment] 2015-04-26 20:55
Mostly fixed. There are still some minor issues on Python 2.7, and `IPDB` needs some refactoring to consume less memory, but it is usable already, and on Python 3 w/o limitations. After fixing tomorrow last issues with Python 2.7 the branch will be merged into master and tagged as a release.

**Comment by takaomag** [comment] 2015-04-27 02:21
For now, I can use the branch since I use Python3.
I want to clarify the usage; can I use IPDB without the temporary solution "Queue" as above (in order to reduce socket objects), even in multi-threads environment ?

**Comment by svinota** [comment] 2015-04-27 06:25
Yep. I used your code, but increased number of instantiation:
```
import logging
from pyroute2 import IPDB

root = logging.getLogger()
root.setLevel(logging.DEBUG)


def get_routes():
    with IPDB() as ipdb:
        routes = ipdb.routes
        {
            dst: routes[dst].dump()
            for dst in routes.keys()
        }

for i in range(2000):
    get_routes()
    print('{}: OK'.format(i))
```

It works.

Using only one IPDB instance also should work. The only question is how often you plan to instantiate IPDB: its start requires costs in terms of RTNL requests, but its runtime costs in terms of parsing broadcast RTNL messages.

Thus, IPDB create & release will be cheaper when it will be done rarely, and in case of frequent requests to IPDB will be cheaper to instantiate it once and then keep running instance.

Offtopic: pls keep in mind also that you always can use the low-level synchronous IPRoute, if you don't want complicated IPDB machinery. IPRoute doesn't require any significant time to start up, doesn't listen for broadcast messages by default, and just provides plain direct netlink API to the kernel.

**Comment by takaomag** [comment] 2015-04-27 08:16
Actually, my script which depends on pyroute2 has several threads.
Once main thread catches a "container start" envent, one of the threads uses IPDB() several times in order to configure the container network. Thus, if so many docker containers starts up at once, many (number of threads x several times) IPDB() object will be created.

The summary of my method is as follows (this may be hard to read, sorry);

```
try:
    with IPDB() as ipdb:
        default_route_mtu = ipdb.by_index[ipdb.routes['default']['oif']]['mtu']
        with IPDB(nl=NetNS(some_netns_name)) as ipdb_netns:
            for vid, _ in vlan_addr_map.items():
                ipdb.create(
                    kind='veth',
                    ifname=some_tap_if_name,
                    peer=some_tap_peer_if_name,
                    mtu=some_mtu_value,
                    txqueuelen=some_txqlen_value
                ).commit()
                # Call ovs-vsctl here, in order to add-port and set-port.
                # Call ovs-ofctl here, in order to add-flow.

            for vid, addr_map in vlan_addr_map.items():
                ipdb.by_name[some_tap_if_name].up().commit()

                with ipdb.by_name[some_tap_peer_if_name] as container_if:
                    container_if.net_ns_fd = some_netns_name

                with ipdb_netns.by_name[some_tap_peer_if_name] as container_if:
                    for addr_label, addr in addr_map.items():
                        container_if.add_ip(str(addr))
                    container_if.mtu = some_mtu_value
                    container_if.txqlen = some_txqlen_value
                    container_if.up()
                    container_if.ifname = some_container_if_name

            for dst, route_kwargs in net_config['routes'].items():
                dst = str(dst)
                oif = ipdb_netns.by_name[some_container_if_name]['index']
                if dst in ipdb_netns.routes.keys():
                    with ipdb_netns.routes[str(dst)] as route:
                        route.oif = oif
                        route.metrics = route_kwargs['metrics']
                else:
                    ipdb_netns.routes.add(
                        dst=str(dst),
                        oif=oif,
                        **route_kwargs
                    ).commit()
except Exception as exc:
    with IPDB() as ipdb:
        for vif_cfg in net_config['vlans'].values():
            # Call ovs-ovsctl heare, in order to delete failed port.
            try:
                ipdb.by_name[some_tap_if_name].remove().commit()
            except:
                pass
    try:
        pyroute2.netns.remove(some_netns_name)
    except:
        pass
    raise
```

> Offtopic: pls keep in mind also that you always can use the low-level synchronous IPRoute,

It seems IPRoute would be better for me.
And, with long-running IPDB() object, I can not use `with ipdb:` syntax since it calls `release()` method on `__exit__` which will let later `commit()` fails because of transaction is closed.

**Comment by svinota** [comment] 2015-04-27 08:47
Pls notice, that pyroute2 transparently supports ovs bridges like any normal bridges: you can create, delete the ovs bridge (`kind='ovs-bridge'` or `kind='openvswitch'`), add and remove ports to/from it.

A sample session to create an ovs bridge, veth interface, add one veth to ovs and move another to a netns (created beforehands somehow):
```
In [1]: from pyroute2 import IPRoute

In [2]: ipr = IPRoute()

In [3]: ipr.link_create(ifname='br-mgmt', kind='ovs-bridge')
Out[3]: 
[{'event': 'NLMSG_ERROR',
  'header': {'error': None,
   'flags': 0,
   'length': 40,
   'pid': 23365,
   'sequence_number': 255,
   'type': 2}}]

In [4]: idx = ipr.link_lookup(ifname='br-mgmt')[0]

In [5]: ipr.link_create(ifname='host-port0', kind='veth', peer='docker-port0')
Out[5]: 
[{'event': 'NLMSG_ERROR',
  'header': {'error': None,
   'flags': 0,
   'length': 36,
   'pid': 23365,
   'sequence_number': 257,
   'type': 2}}]

In [6]: hport = ipr.link_lookup(ifname='host-port0')[0]

In [7]: dport = ipr.link_lookup(ifname='docker-port0')[0]

In [8]: ipr.link('set', index=hport, master=idx)
Out[8]: 
[{'event': 'NLMSG_ERROR',
  'header': {'error': None,
   'flags': 0,
   'length': 40,
   'pid': 23365,
   'sequence_number': 260,
   'type': 2}}]

In [9]: ipr.link('set', index=dport, net_ns_fd='test')
Out[9]: 
[{'event': 'NLMSG_ERROR',
  'header': {'error': None,
   'flags': 0,
   'length': 36,
   'pid': 23365,
   'sequence_number': 263,
   'type': 2}}]
```

**Comment by takaomag** [comment] 2015-04-27 09:01
Oh, I have to test it and refactor my code !
Fow now, I don't have enough time to refactor, I will do it next week.

pyroute2 is quite useful for me. Thanks !

**Comment by svinota** [comment] 2015-04-27 12:42
0.3.7 is out and uploaded to pypi, the branch is merged into the master and will be dropped soon.

If there will be any issues, ping me pls.

The bug report reassigned to 0.3.8 — not closing it, since there probably more work will be needed.

**Comment by takaomag** [comment] 2015-04-27 13:11
Thank you for your quick fix !

**Comment by svinota** [comment] 2015-04-27 13:16
You're welcome!

**Comment by svinota** [comment] 2015-05-05 08:10
Related issue: https://github.com/svinota/pyroute2/issues/132

Looks like the fix here introduced a bug. Reproducible on Python2 and with IPRoute. Fixing.

**Comment by svinota** [comment] 2015-05-05 15:20
Used completely different approach. No gc hacks, no explicit `close()` calls.

Should work anyways. Would you be so kind to check, did it break anything in your code? Thanks!

**Comment by svinota** [comment] 2015-05-06 12:05
0.3.8 with the fix is rolled out:

https://github.com/svinota/pyroute2/releases/tag/0.3.8

Also available on pypi: https://pypi.python.org/pypi/pyroute2

If the issue will reappear, reopen the ticket please. Thanks!

**Closed by svinota** 2015-05-06 12:05 UTC
Labels: bug, on check
