### ISSUE TITLE
IPDB : Cannot commit new interface when dhcpcd "noipv4" option is set for said interface

### ISSUE THREAD

**Issue by furest** [svinota/pyroute2#602] opened 2019-05-07 19:53 UTC
Problem:
Exception` pyroute2.ipdb.exceptions.CommitException: target flags is not set` is thrown when committing a new interface with IPDB if dhcpcd.conf option "noipv4" is set.

Current environment : 
-Raspberry pi 3 B with Raspbian 9 (Stretch)
-Python 3.5.3
-pyroute2 0.5.5
Steps : 
- Add following lines to dhcpcd.conf
```
interface vxlan0
noipv4
```
- Execute python script :
```
from pyroute2 import IPDB
ip = IPDB()
with ip.create(ifname='vxlan0', kind='vxlan', vxlan_id=42, vxlan_group='172.16.1.1', 
vxlan_port=4789) as vxlan:
     vxlan.up()
```

Expected : 

- No error thrown.

Result : 
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/transactional.py", line 209, in __exit__
    self.commit()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/interfaces.py", line 1072, in commit
    raise error
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/interfaces.py", line 853, in commit
    transaction.wait_all_targets()
  File "/usr/local/lib/python3.5/dist-packages/pyroute2/ipdb/transactional.py", line 507, in wait_all_targets
    raise CommitException('target %s is not set' % key)
pyroute2.ipdb.exceptions.CommitException: target flags is not set
```

**Comment by svinota** [comment] 2019-05-08 08:49
Thanks, investigating

**Comment by briantsaunders** [comment] 2019-05-11 13:38
Not sure if this is helpful or not but I've been experiencing a similar issue running pyroute2 in Ubuntu 18.04.2. 

 I've found that this sequence does not work (up'ing the interface before commit):

```
>>> ipdb.create(kind="vxlan", ifname="vxlan100", vxlan_id=100, vxlan_learning=False, vxlan_local="192.168.0.2", vxlan_group="192.168.0.5")
{'ifname': 'vxlan100', 'index': 0, 'kind': 'vxlan', 'ipdb_scope': 'create', 'ipdb_priority': 0, 'vlans': (), 'ipaddr': (), 'ports': ()}
>>> ipdb.interfaces["vxlan100"].up()
{'ifname': 'vxlan100', 'index': 0, 'kind': 'vxlan', 'ipdb_scope': 'create', 'ipdb_priority': 0, 'vlans': (), 'ipaddr': (), 'ports': ()}
>>> ipdb.interfaces["vxlan100"].commit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ipdb/interfaces.py", line 1075, in commit
    raise error
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ipdb/interfaces.py", line 855, in commit
    transaction.wait_all_targets()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ipdb/transactional.py", line 507, in wait_all_targets
    raise CommitException('target %s is not set' % key)
pyroute2.ipdb.exceptions.CommitException: target flags is not set
>>>
```
But this sequence does work (up'ing interface after commit):
```
>>> ipdb.create(kind="vxlan", ifname="vxlan100", vxlan_id=100, vxlan_learning=False, vxlan_local="192.168.0.2", vxlan_group="192.168.0.5")
{'ifname': 'vxlan100', 'index': 0, 'kind': 'vxlan', 'ipdb_scope': 'create', 'ipdb_priority': 0, 'vlans': (), 'ipaddr': (), 'ports': ()}
>>> ipdb.interfaces["vxlan100"].commit()
{'address': '42:01:a0:e3:60:05', 'broadcast': 'ff:ff:ff:ff:ff:ff', 'ifname': 'vxlan100', 'mtu': 1500, 'qdisc': 'noop', 'txqlen': 1000, 'operstate': 'DOWN', 'linkmode': 0, 'group': 0, 'promiscuity': 0, 'num_tx_queues': 1, 'num_rx_queues': 1, 'carrier': 1, 'carrier_changes': 0, 'proto_down': 0, 'gso_max_segs': 65535, 'gso_max_size': 65536, 'xdp': '05:00:02:00:00:00:00:00', 'carrier_up_count': '00:00:00:00', 'carrier_down_count': '00:00:00:00', 'index': 28, 'flags': 4098, 'kind': 'vxlan', 'vxlan_id': 100, 'vxlan_group': '192.168.0.5', 'vxlan_local': '192.168.0.2', 'vxlan_ttl': 0, 'vxlan_tos': 0, 'vxlan_learning': 0, 'vxlan_ageing': 300, 'vxlan_limit': 0, 'vxlan_port_range': {'low': 0, 'high': 0}, 'vxlan_proxy': 0, 'vxlan_rsc': 0, 'vxlan_l2miss': 0, 'vxlan_l3miss': 0, 'vxlan_port': 8472, 'vxlan_udp_csum': 1, 'vxlan_udp_zero_csum6_tx': 0, 'vxlan_udp_zero_csum6_rx': 0, 'vxlan_remcsum_tx': 0, 'vxlan_remcsum_rx': 0, 'vxlan_collect_metadata': 0, 'ipdb_scope': 'system', 'ipdb_priority': 0, 'vlans': (), 'ipaddr': (), 'ports': (), 'family': 0, 'ifi_type': 1, 'unknown': {'header': {'length': 8, 'type': 26}}, 'neighbours': ()}
>>> ipdb.interfaces["vxlan100"].up()
{'address': '42:01:a0:e3:60:05', 'broadcast': 'ff:ff:ff:ff:ff:ff', 'ifname': 'vxlan100', 'mtu': 1500, 'qdisc': 'noop', 'txqlen': 1000, 'operstate': 'DOWN', 'linkmode': 0, 'group': 0, 'promiscuity': 0, 'num_tx_queues': 1, 'num_rx_queues': 1, 'carrier': 1, 'carrier_changes': 0, 'proto_down': 0, 'gso_max_segs': 65535, 'gso_max_size': 65536, 'xdp': '05:00:02:00:00:00:00:00', 'carrier_up_count': '00:00:00:00', 'carrier_down_count': '00:00:00:00', 'index': 28, 'flags': 4098, 'kind': 'vxlan', 'vxlan_id': 100, 'vxlan_group': '192.168.0.5', 'vxlan_local': '192.168.0.2', 'vxlan_ttl': 0, 'vxlan_tos': 0, 'vxlan_learning': 0, 'vxlan_ageing': 300, 'vxlan_limit': 0, 'vxlan_port_range': {'low': 0, 'high': 0}, 'vxlan_proxy': 0, 'vxlan_rsc': 0, 'vxlan_l2miss': 0, 'vxlan_l3miss': 0, 'vxlan_port': 8472, 'vxlan_udp_csum': 1, 'vxlan_udp_zero_csum6_tx': 0, 'vxlan_udp_zero_csum6_rx': 0, 'vxlan_remcsum_tx': 0, 'vxlan_remcsum_rx': 0, 'vxlan_collect_metadata': 0, 'ipdb_scope': 'system', 'ipdb_priority': 0, 'vlans': (), 'ipaddr': (), 'ports': (), 'family': 0, 'ifi_type': 1, 'unknown': {'header': {'length': 8, 'type': 26}}, 'neighbours': ()}
>>> ipdb.interfaces["vxlan100"].commit()
{'address': '42:01:a0:e3:60:05', 'broadcast': 'ff:ff:ff:ff:ff:ff', 'ifname': 'vxlan100', 'mtu': 1500, 'qdisc': 'noqueue', 'txqlen': 1000, 'operstate': 'UNKNOWN', 'linkmode': 0, 'group': 0, 'promiscuity': 0, 'num_tx_queues': 1, 'num_rx_queues': 1, 'carrier': 1, 'carrier_changes': 0, 'proto_down': 0, 'gso_max_segs': 65535, 'gso_max_size': 65536, 'xdp': '05:00:02:00:00:00:00:00', 'carrier_up_count': '00:00:00:00', 'carrier_down_count': '00:00:00:00', 'index': 28, 'flags': 69699, 'kind': 'vxlan', 'vxlan_id': 100, 'vxlan_group': '192.168.0.5', 'vxlan_local': '192.168.0.2', 'vxlan_ttl': 0, 'vxlan_tos': 0, 'vxlan_learning': 0, 'vxlan_ageing': 300, 'vxlan_limit': 0, 'vxlan_port_range': {'low': 0, 'high': 0}, 'vxlan_proxy': 0, 'vxlan_rsc': 0, 'vxlan_l2miss': 0, 'vxlan_l3miss': 0, 'vxlan_port': 8472, 'vxlan_udp_csum': 1, 'vxlan_udp_zero_csum6_tx': 0, 'vxlan_udp_zero_csum6_rx': 0, 'vxlan_remcsum_tx': 0, 'vxlan_remcsum_rx': 0, 'vxlan_collect_metadata': 0, 'ipdb_scope': 'system', 'ipdb_priority': 0, 'vlans': (), 'ipaddr': (), 'ports': (), 'family': 0, 'ifi_type': 1, 'unknown': {'header': {'length': 8, 'type': 26}}, 'neighbours': ()}
>>>
```

**Comment by svinota** [comment] 2019-05-12 11:45
Looks like a race with a third-party software trying to configure the interface at the same time.

As a workaround — until we find a better way to handle that — I may suggest the way described by @briantsaunders , to configure the interface in several steps.

If you have some time to play around, I would ask you also to check if that will work (pls run the master branch):

```python
from pyroute2 import NDB


with NDB() as ndb:
    (ndb
     .interfaces
     .create(ifname='vxlan0',
             kind='vxlan',
             vxlan_group='172.16.254.155',
             vxlan_id=42,
             vxlan_port=4789)
     .set('state', 'up')
     .commit())
```

(NDB will obsolete IPDB in two-three releases, so this feedback would be also important)

**Comment by briantsaunders** [comment] 2019-05-12 15:11
Tested on same Ubuntu 18.04.2 VM (after uninstalling pyroute2 0.5.5 and installing master branch in python3.6) but getting an error upon commit (not immediate, 2 second delay or so before it throws).

```
vagrant@site1router:/vagrant$ sudo pip3 show pyroute2
Name: pyroute2
Version: 0.5.5.post146
Summary: Python Netlink library
Home-page: https://github.com/svinota/pyroute2
Author: Peter V. Saveliev
Author-email: peter@svinota.eu
License: dual license GPLv2+ and Apache v2
Location: /usr/local/lib/python3.6/dist-packages
Requires:
vagrant@site1router:/vagrant$ sudo python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyroute2 import NDB
>>> with NDB() as ndb:
...     with ndb.interfaces.create(kind="vxlan", ifname="vxlan100", vxlan_local="192.168.0.2", vxlan_group="192.168.0.5", vxlan_id=100, vxlan_learning=False) as i:
...         i.set("state", "up")
...
{'flags': 0, 'state': 'up', 'kind': 'vxlan', 'ifname': 'vxlan100', 'vxlan_local': '192.168.0.2', 'vxlan_group': '192.168.0.5', 'vxlan_id': 100, 'vxlan_learning': False, 'target': 'localhost'}
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 101, in __exit__
    self.commit()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 251, in commit
    raise e_i
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 242, in commit
    return self.apply()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 417, in apply
    raise Exception('lost sync in apply()')
Exception: lost sync in apply()
>>>
```
Even though it throws this error it still creates the VXLAN interface and it's operational.

**Comment by svinota** [comment] 2019-05-12 15:28
Thanks!

**Comment by svinota** [comment] 2019-05-12 20:48
@briantsaunders I still cannot reproduce. May I ask you to:
1. pull from the master branch
2. run this code below
3. remove any sensitive information from files `ndb.log` and `ndb.schema`
4. gzip / attach them here or send by mail?

Thanks a lot!

the code:
```
>>> from pyroute2 import NDB
>>> with NDB(log='ndb.log', debug=True) as ndb:
...     with ndb.interfaces.create(kind="vxlan", ifname="vxlan100", vxlan_local="192.168.0.2", vxlan_group="192.168.0.5", vxlan_id=100, vxlan_learning=False) as i:
...         i.set("state", "up")
...     ndb.schema.export_debug('ndb.schema')
...
```

**Comment by briantsaunders** [comment] 2019-05-13 01:14
Pulled from master and re-installed.  Didn't see any files outputted called ndb.schema though.

```
vagrant@site1router:~$ pip3 show pyroute2
Name: pyroute2
Version: 0.5.5.post149
Summary: Python Netlink library
Home-page: https://github.com/svinota/pyroute2
Author: Peter V. Saveliev
Author-email: peter@svinota.eu
License: dual license GPLv2+ and Apache v2
Location: /usr/local/lib/python3.6/dist-packages
Requires:
vagrant@site1router:~$ sudo python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyroute2 import NDB
>>> with NDB(log='ndb.log', debug=True) as ndb:
...     with ndb.interfaces.create(kind="vxlan", ifname="vxlan100", vxlan_local="192.168.0.2", vxlan_group="192.168.0.5", vxlan_id=100, vxlan_learning=False) as i:
...         i.set("state", "up")
...     ndb.schema.export_debug('ndb.schema')
...
{'flags': 0, 'state': 'up', 'kind': 'vxlan', 'ifname': 'vxlan100', 'vxlan_local': '192.168.0.2', 'vxlan_group': '192.168.0.5', 'vxlan_id': 100, 'vxlan_learning': False, 'target': 'localhost'}
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 101, in __exit__
    self.commit()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 251, in commit
    raise e_i
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 242, in commit
    return self.apply()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 417, in apply
    raise Exception('lost sync in apply()')
Exception: lost sync in apply()
>>>
```

[ndb.log](https://github.com/svinota/pyroute2/files/3170805/ndb.log)

**Comment by svinota** [comment] 2019-05-13 08:36
@briantsaunders and the last time (I hope). Sorry for annoying, but since I can not reproduce it, I have to rely on post mortem. But the more important is to find the error. The last master, and the code:
```python
from pyroute2 import NDB
with NDB(log='ndb.log', debug=True) as ndb:
     with ndb.interfaces.create(kind="vxlan",
                                ifname="vxlan100",
                                vxlan_local="192.168.0.2",
                                vxlan_group="192.168.0.5",
                                vxlan_id=100,
                                vxlan_learning=False) as i:
         i.set("state", "up")
     ndb.schema.export_debug('ndb.schema')
```

**Comment by briantsaunders** [comment] 2019-05-13 11:54
No worries, happy to help!  I am still not seeing the ```ndb.schema``` file.  If you're a vagrant user I'm using the following [vagrant box](https://app.vagrantup.com/briantsaunders/boxes/frrouting-stable-7.0) for testing.  It's essentially the ubuntu/bionic64 box with FRRouting installed.

```
vagrant@site1router:~$ pip3 show pyroute2
Name: pyroute2
Version: 0.5.5.post152
Summary: Python Netlink library
Home-page: https://github.com/svinota/pyroute2
Author: Peter V. Saveliev
Author-email: peter@svinota.eu
License: dual license GPLv2+ and Apache v2
Location: /usr/local/lib/python3.6/dist-packages
Requires:
vagrant@site1router:~$ sudo python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyroute2 import NDB
>>> with NDB(log='ndb.log', debug=True) as ndb:
...     with ndb.interfaces.create(kind="vxlan",ifname="vxlan100",vxlan_local="192.168.0.2",vxlan_group="192.168.0.5",vxlan_id=100,vxlan_learning=False) as i:
...         i.set("state", "up")
...     ndb.schema.export_debug('ndb.schema')
...
{'flags': 0, 'state': 'up', 'kind': 'vxlan', 'ifname': 'vxlan100', 'vxlan_local': '192.168.0.2', 'vxlan_group': '192.168.0.5', 'vxlan_id': 100, 'vxlan_learning': False, 'target': 'localhost'}
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 101, in __exit__
    self.commit()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 251, in commit
    raise e_i
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 242, in commit
    return self.apply()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 417, in apply
    raise Exception('lost sync in apply()')
Exception: lost sync in apply()
>>>
```

[ndb.log](https://github.com/svinota/pyroute2/files/3172699/ndb.log)

**Comment by svinota** [comment] 2019-05-13 17:17
@briantsaunders 
```
...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
```
But it looks like I have not this key. Anyway, it looks like I found at least one issue thanks to your traces. If there will be any `ndb.schema` also, it would be useful too, but I believe I found the root cause, and I'm fixing it now.

**Comment by svinota** [comment] 2019-05-13 19:01
@furest Please check, if it works for you now.

And, if it's possible, with NDB also (see the code in the beginning of the thread)

**Comment by svinota** [comment] 2019-05-13 19:09
@briantsaunders it may start working now, but not for sure :) I still can not start the vagrant image, probably some PC architecture related issue. If it doesn't, pls try to collect the `ndb.log` (most important) and the `ndb.schema` (less, but also important)

**Comment by briantsaunders** [comment] 2019-05-14 01:53
Still not working for me unfortunately.  This time around I tried on the stock [ubuntu/bionic64](https://app.vagrantup.com/ubuntu/boxes/bionic64) to rule out maybe something funky with software I had on the other.

```
vagrant@ubuntu-bionic:/vagrant$ pip3 show pyroute2
Name: pyroute2
Version: 0.5.5.post155
Summary: Python Netlink library
Home-page: https://github.com/svinota/pyroute2
Author: Peter V. Saveliev
Author-email: peter@svinota.eu
License: dual license GPLv2+ and Apache v2
Location: /usr/local/lib/python3.6/dist-packages
Requires:
Required-by:
vagrant@ubuntu-bionic:/vagrant$ sudo python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyroute2 import NDB
>>> with NDB(log='ndb.log', debug=True) as ndb:
...     with ndb.interfaces.create(kind="vxlan",ifname="vxlan100",vxlan_local="192.168.0.2",vxlan_group="192.168.0.5",vxlan_id=100,vxlan_learning=False) as i:
...         i.set("state", "up")
...     ndb.schema.export_debug('ndb.schema')
...
{'flags': 0, 'state': 'up', 'kind': 'vxlan', 'ifname': 'vxlan100', 'vxlan_local': '192.168.0.2', 'vxlan_group': '192.168.0.5', 'vxlan_id': 100, 'vxlan_learning': False, 'target': 'localhost'}
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 101, in __exit__
    self.commit()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 251, in commit
    raise e_i
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 242, in commit
    return self.apply()
  File "/usr/local/lib/python3.6/dist-packages/pyroute2/ndb/objects/__init__.py", line 417, in apply
    raise Exception('lost sync in apply()')
Exception: lost sync in apply()
>>>
```
[ndb.log](https://github.com/svinota/pyroute2/files/3175503/ndb.log)

**Comment by svinota** [comment] 2019-05-14 06:39
@briantsaunders finally, reproduced. Thanks! Working on it.

**Comment by svinota** [comment] 2019-05-14 11:21
@briantsaunders thanks for the help. Now it should work as expected.

**Comment by furest** [comment] 2019-05-14 12:22
Sorry for the wait...

I tried the original test again (the one in the first post) and I still have the same error.
(I cloned master branch and installed using pip3)
However I did the 3 tests with NDB and didn't seem to have any issue...
Am I missing something? (I've tried to catch up what happened as best as I could)

**Comment by svinota** [comment] 2019-05-14 14:33
@furest no, it was me missed one commit. Here it comes, IPDB should work now also.

**Comment by furest** [comment] 2019-05-14 14:43
It works, awesome!
Thanks for the work!

**Comment by briantsaunders** [comment] 2019-05-14 14:50
Works for me as well, using both methods (IPDB and NDB).  With IPDB was able to up the interface and then perform a commit afterwards without error.

**Comment by svinota** [comment] 2019-05-14 15:03
Ok, good. Then I close the issue.

**Closed by svinota** 2019-05-14 15:03 UTC
Labels: bug
