### ISSUE TITLE
Please include unit tests in release

### ISSUE THREAD

**Issue by zulcss** [svinota/pyroute2#329] opened 2017-01-05 13:45 UTC
In order for the Ubuntu maintainers to have better confidence in pyroute2's usage in Ubuntu please include the unit tests in the source tarball so we can run the unit tests when we distribute the package in the Ubuntu archive.

**Comment by svinota** [comment] 2017-01-06 11:19
The problem is that mostly tests are functional ones, and require root (or at least CAP_NET_ADMIN) privileges to create/modify/destroy network object in the kernel. Not sure that the Ubuntu maintainers will be happy with that.

So I'll move unit tests in a separate test module and bundle it in the source tarball, probably it's the time, finally. Thanks for the issue, will be done in 0.4.13 in a week or two.

**Comment by svinota** [comment] 2017-01-06 11:20
Dependent issue: https://bugs.launchpad.net/ubuntu/+source/pyroute2/+bug/1653527

**Comment by svinota** [comment] 2017-01-13 13:29
Pls check out the `ubuntu-tests` branch.
```bash
# create the tarball
make dist
# untar and run the tests
cd dist
tar xf *
cd pyroute2*
nosetests -v tests/unit/
```

The number of the unit tests are not so big yet, and will increase from release to release. The reason is that the CI is focused on the functional tests (including some Ubuntu kernels :), implying that the API is more or less stable.

As being unit tests, they do not require root privileges to run. Please notice, that the unit tests per se do not guarantee anything, only performing some static API checks.

If the scheme proposed fits your needs, this branch will be merged into the master and will be included in the next release. If not, also don't hesitate to comment.

**Comment by zulcss** [comment] 2017-01-13 13:34
Yes this would be awesome..

**Comment by svinota** [comment] 2017-02-19 16:57
Unit tests are from 0.4.13 on included in the bundle. Pls keep in mind, that 'cause of the nature of the library, unit tests don't cover 100% code, and never will. The primary target is still functional tests, that aren't included in the bundle (yet) and that require root access to the system they run on.

**Closed** 2017-02-19 16:57 UTC
Labels: fixed, fr
