### ISSUE TITLE
Possible bug IPDB/NetNS with OVS bridges

### ISSUE THREAD

**Issue by jazzmes** [svinota/pyroute2#104] opened 2015-02-18 20:56 UTC
So, this is working with the current 0.3.4 version but not with the master.
I getting this problem when opening the network namespace after adding an OVS tap interface to it. 
Test code:
```python
import traceback
from pyroute2.ipdb import IPDB
from pyroute2.netns import NetNS

if __name__ == "__main__":
    # * before-hand create bridge and interface
    # sudo ovs-vsctl add-br br-test
    # sudo ovs-vsctl add-port br-test tap-test -- set Interface tap-test type=internal

    bridge_name = "br-test"
    ns_name = "ns-test"
    tap_name = "tap-test"

    print("connect and release: %s" % ns_name)
    ipdb_ns = IPDB(nl=NetNS(ns_name))
    ipdb_ns.release()

    ip = IPDB()
    try:
        print("loading interface: '%s'" % tap_name)
        with getattr(ip.interfaces, tap_name) as i:
            print("adding interface to netns '%s'" % ns_name)
            i.net_ns_fd = ns_name
    except Exception as e:
        print(traceback.format_exc())
    finally:
        ip.release()

    print("connect and release again: %s" % ns_name)
    ipdb_ns = IPDB(nl=NetNS(ns_name))
    ipdb_ns.release()
    # print("remove netns: %s" % ns_name)
    # netns.remove(ns_name)
```

Output:
```
connect and release: ns-test
loading interface: 'tap-test'
adding interface to netns 'ns-test'
connect and release again: ns-test
Traceback (most recent call last):
  File "tests/test_bug_pyroute2.py", line 90, in <module>
    ipdb_ns = IPDB(nl=NetNS(ns_name))
  File "/usr/lib/python3.3/site-packages/pyroute2/ipdb/__init__.py", line 405, in __init__
    self.initdb(nl)
  File "/usr/lib/python3.3/site-packages/pyroute2/ipdb/__init__.py", line 441, in initdb
    links = self.nl.get_links()
  File "/usr/lib/python3.3/site-packages/pyroute2/iproute.py", line 218, in get_links
    result.extend(self.nlm_request(msg, RTM_GETLINK, msg_flags))
  File "/usr/lib/python3.3/site-packages/pyroute2/netlink/nlsocket.py", line 758, in nlm_request
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/usr/lib/python3.3/site-packages/pyroute2/netlink/nlsocket.py", line 625, in get
    raise msg['header']['error']
pyroute2.netlink.NetlinkError: (70, 'Communication error on send')
```

Again, only happening in the master version, and I was not able to replicate it without using OVS ports.
Any clue why this happens?

**Comment by svinota** [comment] 2015-02-18 23:01
Thanks for the report — will investigate it tomorrow.

**Comment by svinota** [comment] 2015-02-18 23:26
Strange. I can not reproduce it:
```
  $ sudo python test.py 
  connect and release: test
  loading interface: 'ovsp1'
  adding interface to netns 'test'
  connect and release again: test
```
Tomorrow will try to add more debug into the master and we will try to collect info from your box.

**Comment by jazzmes** [comment] 2015-02-19 00:48
Tried in a different machine and got the same error (with both python2 and python3 in Fedora 20).
It works fine with version 0.3.4 installed with pip.
This is a netlink error, right? I cannot find any reference on the error.

**Comment by svinota** [comment] 2015-02-19 06:42
No, that's pyroute2 netlink proxy error. And there are two issues, actually: the error itself, and the diagnostics.

That's good that the error is reproducible.

**Comment by svinota** [comment] 2015-02-19 10:10
Tried on:

```
$ cat /etc/debian_version 
8.0
$ uname -r
3.16.0-4-amd64
$ dpkg -l | awk '/openvswitch-switch/ {print $3}'
2.3.0+git20140819-3
```

and
```
$ cat /etc/redhat-release 
Fedora release 20 (Heisenbug)
$ uname -r
3.17.8-200.fc20.x86_64
$ rpm -qa | grep openvswitch
openvswitch-2.3.1-2.git20150113.fc20.x86_64
```

Still not reproduced with the code you provided.

So pls wait — this evening I will provide some more diagnostic tools for the case. Thanks a lot for the patience!

Rlated issue: #106

**Comment by svinota** [comment] 2015-02-19 10:54
@jazzmes  — could you pls collect logs with the latest master version?

**Comment by jazzmes** [comment] 2015-02-19 17:01
```
connect and release: ns-test
ERROR:root:Traceback (most recent call last):
  File "/home/lama/tmp/pyroute2/pyroute2/proxy.py", line 38, in handle
    ret = plugin(data, self.nl)
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/rtnl/ifinfmsg.py", line 587, in proxy_linkinfo
    msg.encode()
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/rtnl/ifinfmsg.py", line 211, in encode
    return super(ifinfbase, self).encode()
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/__init__.py", line 881, in encode
    self.encode_nlas()
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/__init__.py", line 1008, in encode_nlas
    nla.encode()
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/__init__.py", line 881, in encode
    self.encode_nlas()
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/__init__.py", line 1008, in encode_nlas
    nla.encode()
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/__init__.py", line 1205, in encode
    nla_base.encode(self)
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/__init__.py", line 849, in encode
    length = len(value) + 1
TypeError: object of type 'bool' has no len()

Traceback (most recent call last):
  File "test_bug_pyroute2.py", line 75, in <module>
    ipdb_ns = IPDB(nl=NetNS(ns_name))
  File "/home/lama/tmp/pyroute2/pyroute2/ipdb/__init__.py", line 405, in __init__
    self.initdb(nl)
  File "/home/lama/tmp/pyroute2/pyroute2/ipdb/__init__.py", line 441, in initdb
    links = self.nl.get_links()
  File "/home/lama/tmp/pyroute2/pyroute2/iproute.py", line 218, in get_links
    result.extend(self.nlm_request(msg, RTM_GETLINK, msg_flags))
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/nlsocket.py", line 758, in nlm_request
    ret = self.get(msg_seq=msg_seq, terminate=terminate)
  File "/home/lama/tmp/pyroute2/pyroute2/netlink/nlsocket.py", line 625, in get
    raise msg['header']['error']
pyroute2.netlink.NetlinkError: (70, 'Communication error on send')
```

**Comment by svinota** [comment] 2015-02-19 18:27
Thanks!

**Comment by svinota** [comment] 2015-02-19 18:54
The root cause found. Fixing.

**Comment by svinota** [comment] 2015-02-19 19:52
Should be fixed now, could you pls check?

Also — provide pls platform details, distro/kernel/ovs version

Thanks!

**Comment by jazzmes** [comment] 2015-02-19 20:04
Yes, my test runs fine now! Thanks!
```
$ cat /etc/fedora-release 
Fedora release 20 (Heisenbug)
$ uname -r
3.16.7-200.fc20.x86_64
$ rpm -qa | grep openvswitch
openvswitch-2.3.1-1.fc20.x86_64
```
Any clue why it was triggered in this particular environment?

**Comment by svinota** [comment] 2015-02-19 20:13
Kernel didn't provide IFLA_INFO_KIND for an interface, and sysfs wasn't available for some reason. The library repacks netlink packets in such cases, adding needed info (thus IPDB work in the same way on different platforms — it doesn't see any difference). But the compatibility function was inherited from the old code and wasn't designed well for that case, returning values different types for different cases. In the case of unavailable sysfs it returned False — and ifinfmsg:proxy_linkinfo() method passed this False directly to encoding, where a string was expected.

Now it returns «unknown» interface kind in such cases, but knowing platform specs I can now reproduce it and will work more on the case, so don't close it still.

**Closed** 2015-02-28 19:53 UTC
Labels: bug, fixed
